import type { Communication } from "@/types";

export const communications: Communication[] = [
  // Request req-1 communications (Rothschild airport transfer - completed)
  {
    id: "com-1",
    requestId: "req-1",
    sender: "client",
    senderName: "Alexander Rothschild",
    message: "I need my usual Teterboro pickup tomorrow evening. Arriving at 6 PM sharp. Make sure Heinrich is driving — he knows the protocol.",
    channel: "concierge",
    tags: ["vip"],
    createdAt: "2026-01-14T10:00:00Z",
  },
  {
    id: "com-2",
    requestId: "req-1",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Confirmed, Mr. Rothschild. Heinrich is assigned and will be at the private terminal by 5:30 PM. Maybach S680 is prepped with Krug Grande Cuvée chilled to your preference. Security team has been notified.",
    channel: "concierge",
    tags: ["vip"],
    createdAt: "2026-01-14T10:30:00Z",
  },
  {
    id: "com-3",
    requestId: "req-1",
    sender: "system",
    senderName: "System",
    message: "Request status changed to completed. Trip duration: 42 minutes. No incidents reported.",
    channel: "concierge",
    createdAt: "2026-01-15T19:30:00Z",
  },
  // Request req-2 communications (Rothschild jet charter - in_progress)
  {
    id: "com-4",
    requestId: "req-2",
    sender: "client",
    senderName: "Alexander Rothschild",
    message: "Need a G650 for Aspen this weekend. Six of us plus full ski gear. And please arrange Nobu catering — the omakase selection, not the standard menu.",
    channel: "phone",
    tags: ["vip", "urgent"],
    createdAt: "2026-02-10T14:00:00Z",
  },
  {
    id: "com-5",
    requestId: "req-2",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Good afternoon, Mr. Rothschild. I have two G650 options available for the 28th. Tail N650GX is your preferred aircraft from November — shall I confirm that one? Nobu omakase for 6 is noted. I'll need the passenger manifest for TSA by end of day Thursday.",
    channel: "phone",
    tags: ["vip"],
    createdAt: "2026-02-10T14:15:00Z",
  },
  {
    id: "com-6",
    requestId: "req-2",
    sender: "client",
    senderName: "Alexander Rothschild",
    message: "Yes, N650GX. Manifest attached. Also add ground transport on the Aspen side — two Escalades at the airport.",
    channel: "email",
    tags: ["vip"],
    attachments: [
      {
        id: "att-1",
        name: "passenger_manifest_feb28.pdf",
        type: "application/pdf",
        size: 245000,
        url: "/attachments/att-1/passenger_manifest_feb28.pdf",
      },
    ],
    createdAt: "2026-02-11T09:00:00Z",
  },
  // Request req-3 communications (Victoria helicopter - assigned)
  {
    id: "com-7",
    requestId: "req-3",
    sender: "client",
    senderName: "Victoria Cheng-Worthington",
    message: "Darling, I need a heli from the Peninsula to Grand Lisboa on the 5th. The AW139 please, not the smaller one. And I'll need return around midnight.",
    channel: "whatsapp",
    tags: ["vip"],
    createdAt: "2026-02-18T09:00:00Z",
  },
  {
    id: "com-8",
    requestId: "req-3",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Of course, Mrs. Cheng-Worthington. AW139 confirmed for March 5th. Departure from Peninsula helipad at 2:00 PM, return at midnight from Grand Lisboa. Shall I arrange VIP arrival at the casino as well?",
    channel: "whatsapp",
    tags: ["vip"],
    createdAt: "2026-02-18T09:20:00Z",
  },
  {
    id: "com-9",
    requestId: "req-3",
    sender: "client",
    senderName: "Victoria Cheng-Worthington",
    message: "Yes, full VIP arrival. And have them prepare the Salon Privé. My usual table.",
    channel: "whatsapp",
    tags: ["vip"],
    createdAt: "2026-02-18T09:25:00Z",
  },
  // Request req-4 communications (Victoria wedding fleet - completed)
  {
    id: "com-10",
    requestId: "req-4",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Good news — all four white Phantoms are confirmed for the 20th. Floral arrangements by Moens will be installed the morning of. Route has been surveyed and approved by local authorities.",
    channel: "email",
    tags: ["vip"],
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "com-11",
    requestId: "req-4",
    sender: "client",
    senderName: "Victoria Cheng-Worthington",
    message: "Perfect. Make sure the ribbons match the exact shade of ivory from the sample I sent. Pantone 11-0604 TCX.",
    channel: "email",
    tags: ["vip"],
    attachments: [
      {
        id: "att-2",
        name: "ribbon_color_sample.jpg",
        type: "image/jpeg",
        size: 1200000,
        url: "/attachments/att-2/ribbon_color_sample.jpg",
      },
    ],
    createdAt: "2026-01-10T14:00:00Z",
  },
  {
    id: "com-12",
    requestId: "req-4",
    sender: "system",
    senderName: "System",
    message: "Request completed. All 4 vehicles delivered on schedule. Client satisfaction: excellent.",
    channel: "email",
    createdAt: "2026-01-20T16:00:00Z",
  },
  // Request req-5 communications (Sheikh yacht - action_required)
  {
    id: "com-13",
    requestId: "req-5",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Sheikh Al-Fayed, we have identified three superyachts meeting your specifications for Monaco GP weekend. The 88m 'Eclipse II' with harbor-front position is my top recommendation. Deck plans and crew profiles attached.",
    channel: "concierge",
    tags: ["vip", "urgent"],
    attachments: [
      {
        id: "att-3",
        name: "eclipse_ii_deck_plans.pdf",
        type: "application/pdf",
        size: 5400000,
        url: "/attachments/att-3/eclipse_ii_deck_plans.pdf",
      },
      {
        id: "att-4",
        name: "crew_profiles.pdf",
        type: "application/pdf",
        size: 3200000,
        url: "/attachments/att-4/crew_profiles.pdf",
      },
    ],
    createdAt: "2026-02-05T10:00:00Z",
  },
  {
    id: "com-14",
    requestId: "req-5",
    sender: "client",
    senderName: "Sheikh Omar Al-Fayed",
    message: "Eclipse II looks acceptable. But I need the master suite reconfigured. My designer will send specifications. Also, the chef must be Michelin-starred — no exceptions.",
    channel: "concierge",
    tags: ["vip", "urgent"],
    createdAt: "2026-02-06T15:00:00Z",
  },
  {
    id: "com-15",
    requestId: "req-5",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Understood. We are awaiting the designer's specifications for the master suite. I have shortlisted three Michelin-starred chefs with experience on superyachts. Profiles will follow. ACTION NEEDED: Please have your designer send specs by February 25th to meet the refit deadline.",
    channel: "concierge",
    tags: ["vip", "urgent", "follow-up"],
    createdAt: "2026-02-07T09:00:00Z",
  },
  // Request req-7 communications (Isabelle car - in_progress)
  {
    id: "com-16",
    requestId: "req-7",
    sender: "client",
    senderName: "Isabelle de Montfort",
    message: "Elena, I need the Flying Spur for all of Fashion Week. The driver must know every venue — I cannot be late to Chanel or Dior.",
    channel: "email",
    tags: ["vip"],
    createdAt: "2026-02-05T13:00:00Z",
  },
  {
    id: "com-17",
    requestId: "req-7",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Bonjour Madame de Montfort. Pierre will be your chauffeur — he drove you last season and knows every venue entrance and back route. The Flying Spur in Meteor finish is reserved. I'll share the full schedule once the show calendar is finalized.",
    channel: "email",
    tags: ["vip"],
    createdAt: "2026-02-05T14:30:00Z",
  },
  {
    id: "com-18",
    requestId: "req-7",
    sender: "client",
    senderName: "Isabelle de Montfort",
    message: "Parfait. Also arrange storage in the boot for garment bags — I'll be collecting pieces throughout the week.",
    channel: "whatsapp",
    tags: ["vip"],
    createdAt: "2026-02-06T10:00:00Z",
  },
  // Request req-9 communications (Harrington LAX transfer - completed)
  {
    id: "com-19",
    requestId: "req-9",
    sender: "client",
    senderName: "Robert Harrington",
    message: "Booking S-Class for my LAX arrival on the 18th. Terminal B, landing around 8 PM. Three large bags.",
    channel: "web",
    createdAt: "2026-01-16T09:00:00Z",
  },
  {
    id: "com-20",
    requestId: "req-9",
    sender: "agent",
    senderName: "David Kim",
    message: "Confirmed, Mr. Harrington. Your driver will be waiting at Terminal B arrivals with a name board. S-Class with ample trunk space for your luggage. ETA to Beverly Hills Hotel approximately 35 minutes depending on traffic.",
    channel: "web",
    createdAt: "2026-01-16T09:30:00Z",
  },
  {
    id: "com-21",
    requestId: "req-9",
    sender: "system",
    senderName: "System",
    message: "Trip completed successfully. Duration: 38 minutes.",
    channel: "web",
    createdAt: "2026-01-18T21:30:00Z",
  },
  // Request req-11 communications (Petrova Range Rover - in_progress)
  {
    id: "com-22",
    requestId: "req-11",
    sender: "client",
    senderName: "Natasha Petrova",
    message: "Hi, I'd like a Range Rover from Claridge's to Soho Farmhouse next weekend. The Autobiography if possible — we had one last time and loved it.",
    channel: "phone",
    createdAt: "2026-02-20T11:00:00Z",
  },
  {
    id: "com-23",
    requestId: "req-11",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Hello Ms. Petrova. The Range Rover Autobiography LWB is available for March 7-9. I'll arrange pickup at Claridge's main entrance at 9 AM. Would you like any refreshments stocked in the vehicle?",
    channel: "phone",
    createdAt: "2026-02-20T11:20:00Z",
  },
  {
    id: "com-24",
    requestId: "req-11",
    sender: "client",
    senderName: "Natasha Petrova",
    message: "Still water and some light snacks would be lovely, thank you.",
    channel: "phone",
    createdAt: "2026-02-20T11:25:00Z",
  },
  // Request req-14 communications (Mei Lin jet - assigned)
  {
    id: "com-25",
    requestId: "req-14",
    sender: "client",
    senderName: "Mei Lin Zhang",
    message: "Need Challenger 350 Shanghai to Tokyo for March 12. Four passengers. Can you confirm Mandarin-speaking crew? Also, we have specific dietary requirements — no shellfish for two passengers.",
    channel: "whatsapp",
    createdAt: "2026-02-22T06:00:00Z",
  },
  {
    id: "com-26",
    requestId: "req-14",
    sender: "agent",
    senderName: "David Kim",
    message: "Ms. Zhang, I have a Challenger 350 with Mandarin-fluent crew confirmed. Departure 7 AM from Hongqiao FBO. The caterer has been briefed on the no-shellfish requirement for two guests. I'll send the full flight brief by March 8.",
    channel: "whatsapp",
    createdAt: "2026-02-22T08:00:00Z",
  },
  // Request req-15 communications (Mei Lin car - action_required)
  {
    id: "com-27",
    requestId: "req-15",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Ms. Zhang, the Maybach GLS 600 is reserved for March 13. We still need your meeting itinerary to plan the route and timing. Could you please share it at your earliest convenience?",
    channel: "email",
    tags: ["follow-up"],
    createdAt: "2026-02-21T10:00:00Z",
  },
  {
    id: "com-28",
    requestId: "req-15",
    sender: "client",
    senderName: "Mei Lin Zhang",
    message: "I'll have my assistant send the itinerary by end of this week. There will be at least 4 stops across Pudong and the Bund area.",
    channel: "email",
    createdAt: "2026-02-22T03:00:00Z",
  },
  // Request req-18 communications (Kensington fleet - in_progress)
  {
    id: "com-29",
    requestId: "req-18",
    sender: "client",
    senderName: "Sarah Kensington",
    message: "We need three Phantoms for the charity gala at the V&A on March 2nd. Our celebrity guests require absolute discretion. Tinted windows mandatory. Can you coordinate with our PR team on arrival timing?",
    channel: "concierge",
    tags: ["urgent"],
    createdAt: "2026-02-12T10:00:00Z",
  },
  {
    id: "com-30",
    requestId: "req-18",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Absolutely, Ms. Kensington. Three Phantoms with factory-tinted privacy glass confirmed. I'll need your PR team's contact to coordinate the 30-second interval arrivals at the red carpet. All drivers are NDA-cleared.",
    channel: "concierge",
    tags: ["urgent"],
    createdAt: "2026-02-12T10:45:00Z",
  },
  {
    id: "com-31",
    requestId: "req-18",
    sender: "client",
    senderName: "Sarah Kensington",
    message: "Perfect. PR contact: jessica.hall@kensingtonpr.co.uk. She'll send the exact arrival schedule by February 28th. Each guest will have a personal assistant in the vehicle — please ensure rear seating for 3 in each car.",
    channel: "email",
    tags: ["urgent"],
    attachments: [
      {
        id: "att-5",
        name: "gala_event_brief.pdf",
        type: "application/pdf",
        size: 890000,
        url: "/attachments/att-5/gala_event_brief.pdf",
      },
    ],
    createdAt: "2026-02-13T09:00:00Z",
  },
  // Request req-21 communications (Okafor Lagos - in_progress)
  {
    id: "com-32",
    requestId: "req-21",
    sender: "client",
    senderName: "Amara Okafor",
    message: "I need the S-Class with full security detail for March 3rd Lagos airport pickup. Please ensure the escort team is from our approved provider — Citadel Security.",
    channel: "whatsapp",
    createdAt: "2026-02-18T07:00:00Z",
  },
  {
    id: "com-33",
    requestId: "req-21",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Confirmed, Ms. Okafor. S-Class with armored option and Citadel Security escort arranged. Two lead vehicles and one follow vehicle. Route from Murtala Muhammed to Eko Atlantic has been surveyed. ETA approximately 45 minutes with escort.",
    channel: "whatsapp",
    createdAt: "2026-02-18T09:00:00Z",
  },
  // Request req-23 communications (Rothschild yacht follow-up - action_required)
  {
    id: "com-34",
    requestId: "req-23",
    sender: "client",
    senderName: "Alexander Rothschild",
    message: "Marcus, regarding the Caribbean charter — I want the same captain from last year, Captain Morrison. Also add the Jet Ski package and the 40ft tender, not the 30ft. My kids will be joining this time.",
    channel: "concierge",
    tags: ["vip", "urgent"],
    createdAt: "2026-02-15T08:00:00Z",
  },
  {
    id: "com-35",
    requestId: "req-23",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Mr. Rothschild, Captain Morrison is available and delighted to be aboard again. I'm working on upgrading the tender to the 40ft and adding the full water toys package including Jet Skis. For the children, shall I arrange the youth entertainment coordinator as well? I also need to know ages for safety equipment sizing.",
    channel: "concierge",
    tags: ["vip", "urgent", "follow-up"],
    createdAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "com-36",
    requestId: "req-23",
    sender: "client",
    senderName: "Alexander Rothschild",
    message: "Ages 8 and 11. Yes to the entertainment coordinator. And my wife wants the spa to be fully operational — she was disappointed last time. Make sure the therapist is top-tier.",
    channel: "concierge",
    tags: ["vip"],
    createdAt: "2026-02-16T14:00:00Z",
  },
  // Request req-6 communications (Sheikh jet - new)
  {
    id: "com-37",
    requestId: "req-6",
    sender: "client",
    senderName: "Sheikh Omar Al-Fayed",
    message: "I require a BBJ for my delegation traveling to London on March 15. Twenty passengers. The aircraft must have a full bedroom suite. Catering by Al Reef — they know my requirements.",
    channel: "phone",
    tags: ["vip"],
    createdAt: "2026-02-24T11:00:00Z",
  },
  // Request req-8 communications (Isabelle helicopter - completed)
  {
    id: "com-38",
    requestId: "req-8",
    sender: "agent",
    senderName: "David Kim",
    message: "Mme de Montfort, your Mont Blanc helicopter tour is confirmed for January 25th at 11 AM. Bollinger Rosé will be served during the flight. Landing at Megève at 12:30 PM, and your table at Flocons de Sel is reserved for 1 PM.",
    channel: "whatsapp",
    tags: ["vip"],
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "com-39",
    requestId: "req-8",
    sender: "client",
    senderName: "Isabelle de Montfort",
    message: "Merci David. Can you also arrange transport from Megève back to Chamonix after lunch? Something comfortable — perhaps a Range Rover?",
    channel: "whatsapp",
    tags: ["vip"],
    createdAt: "2026-01-20T11:00:00Z",
  },
  {
    id: "com-40",
    requestId: "req-8",
    sender: "agent",
    senderName: "David Kim",
    message: "Of course! Range Rover Autobiography will be waiting at the restaurant. Driver is familiar with the alpine routes. Estimated drive time: 45 minutes.",
    channel: "whatsapp",
    tags: ["vip"],
    createdAt: "2026-01-20T11:15:00Z",
  },
  {
    id: "com-41",
    requestId: "req-8",
    sender: "system",
    senderName: "System",
    message: "Helicopter tour completed. Client rated experience 5/5. Ground transport completed without issues.",
    channel: "whatsapp",
    createdAt: "2026-01-25T17:00:00Z",
  },
  // Request req-12 communications (Petrova cancelled jet)
  {
    id: "com-42",
    requestId: "req-12",
    sender: "client",
    senderName: "Natasha Petrova",
    message: "I need to cancel the Nice flight. My schedule has changed completely. Apologies for the short notice.",
    channel: "email",
    createdAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "com-43",
    requestId: "req-12",
    sender: "agent",
    senderName: "David Kim",
    message: "Understood, Ms. Petrova. The Citation XLS booking has been cancelled. No cancellation fees apply as we are still outside the 48-hour window. We look forward to assisting you next time.",
    channel: "email",
    createdAt: "2026-02-10T09:30:00Z",
  },
  // Request req-13 communications (Whitfield Tesla - completed)
  {
    id: "com-44",
    requestId: "req-13",
    sender: "client",
    senderName: "Thomas Whitfield",
    message: "Booked via website: Tesla Model S Plaid from SFO to my office at 555 California St. Arriving 3 PM on Jan 22. I prefer electric vehicles whenever available.",
    channel: "web",
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "com-45",
    requestId: "req-13",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Welcome, Mr. Whitfield. Tesla Model S Plaid confirmed. We've noted your EV preference for future bookings. Driver will meet you at Terminal 2 baggage claim with a name board.",
    channel: "web",
    createdAt: "2026-01-20T10:30:00Z",
  },
  // Request req-16 communications (Mendes São Paulo - completed)
  {
    id: "com-46",
    requestId: "req-16",
    sender: "system",
    senderName: "System",
    message: "Booking confirmed via web portal. E-Class, Guarulhos to Fasano Hotel. Driver: Ricardo (Portuguese-speaking). Pickup: 10 PM Jan 28.",
    channel: "web",
    createdAt: "2026-01-25T12:00:00Z",
  },
  {
    id: "com-47",
    requestId: "req-16",
    sender: "agent",
    senderName: "David Kim",
    message: "Mr. Mendes, your E-Class transfer is confirmed. Ricardo will be waiting at the international arrivals hall. He'll have a discreet LLC Car sign. Safe travels.",
    channel: "web",
    createdAt: "2026-01-26T08:00:00Z",
  },
  // Request req-19 communications (Kensington Heathrow - completed)
  {
    id: "com-48",
    requestId: "req-19",
    sender: "client",
    senderName: "Sarah Kensington",
    message: "Need an S-Class for my Heathrow arrival Feb 5. Terminal 5, BA117 from JFK. Going to The Connaught.",
    channel: "email",
    createdAt: "2026-02-03T09:00:00Z",
  },
  {
    id: "com-49",
    requestId: "req-19",
    sender: "agent",
    senderName: "David Kim",
    message: "All set, Ms. Kensington. We'll be tracking BA117 for any delays. Driver will be in the T5 arrivals hall. The Connaught is approximately 45 minutes from Heathrow at that hour.",
    channel: "email",
    createdAt: "2026-02-03T09:45:00Z",
  },
  {
    id: "com-50",
    requestId: "req-19",
    sender: "system",
    senderName: "System",
    message: "Flight BA117 arrived on time. Client picked up at 7:35 AM. Dropped off at The Connaught at 8:45 AM.",
    channel: "email",
    createdAt: "2026-02-05T08:45:00Z",
  },
];
