import type { Communication } from "@/types";

export const communications: Communication[] = [
  // Conversation conv-1 communications (Ashworth airport transfer - converted)
  {
    id: "com-1",
    conversationId: "conv-1",
    sender: "client",
    senderName: "James Ashworth",
    message: "I need my usual Farnborough pickup tomorrow evening. Arriving at 6 PM sharp. Make sure Heinrich is driving — he knows the protocol.",
    channel: "concierge",
    createdAt: "2026-01-14T10:00:00Z",
  },
  {
    id: "com-2",
    conversationId: "conv-1",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Confirmed, Mr. Ashworth. Heinrich is assigned and will be at the TAG Terminal by 5:30 PM. Maybach S680 is prepped with Krug Grande Cuvée chilled to your preference. Security team has been notified.",
    channel: "concierge",
    deliveryStatus: "read",
    createdAt: "2026-01-14T10:30:00Z",
  },
  {
    id: "com-3",
    conversationId: "conv-1",
    sender: "system",
    senderName: "System",
    message: "Booking created. Trip duration: 42 minutes. No incidents reported.",
    channel: "concierge",
    event: {
      type: "booking_created",
      bookingId: "bk-1",
      title: "Farnborough Airport Transfer",
      category: "car",
    },
    createdAt: "2026-01-15T19:30:00Z",
  },
  {
    id: "com-51",
    conversationId: "conv-1",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "concierge",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-1",
      title: "Farnborough Airport Transfer",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-01-15T19:35:00Z",
  },
  {
    id: "com-52",
    conversationId: "conv-1",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £2,959.",
    channel: "concierge",
    event: {
      type: "invoice_created",
      invoiceId: "inv-1",
      invoiceTotal: 2959,
    },
    createdAt: "2026-01-15T19:40:00Z",
  },
  {
    id: "com-53",
    conversationId: "conv-1",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "concierge",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-1",
      invoiceTotal: 2959,
    },
    createdAt: "2026-01-15T19:45:00Z",
  },
  {
    id: "com-54",
    conversationId: "conv-1",
    sender: "system",
    senderName: "System",
    message: "Payment confirmed.",
    channel: "concierge",
    event: {
      type: "payment_confirmed",
      bookingId: "bk-1",
      paymentAmount: 2959,
      paymentMethod: "card",
      invoiceId: "inv-1",
    },
    createdAt: "2026-01-15T20:00:00Z",
  },
  {
    id: "com-55",
    conversationId: "conv-1",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to paid.",
    channel: "concierge",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-1",
      title: "Farnborough Airport Transfer",
      fromStatus: "awaiting_payment",
      toStatus: "paid",
    },
    createdAt: "2026-01-15T20:05:00Z",
  },
  {
    id: "com-56",
    conversationId: "conv-1",
    sender: "system",
    senderName: "System",
    message: "Booking completed.",
    channel: "concierge",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-1",
      title: "Farnborough Airport Transfer",
      fromStatus: "in_progress",
      toStatus: "completed",
    },
    createdAt: "2026-01-15T20:10:00Z",
  },
  // Conversation conv-2 communications (Ashworth jet charter - in_review)
  {
    id: "com-4",
    conversationId: "conv-2",
    sender: "client",
    senderName: "James Ashworth",
    message: "Need a G650 for Newcastle this weekend. Six of us plus luggage. And please arrange Dorchester catering — the full menu, not the standard selection.",
    channel: "phone",
    createdAt: "2026-02-10T14:00:00Z",
  },
  {
    id: "com-5",
    conversationId: "conv-2",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Good afternoon, Mr. Ashworth. I have two G650 options available for the 28th. Tail G-LUXE is your preferred aircraft from November — shall I confirm that one? Dorchester full menu for 6 is noted. I'll need the passenger manifest by end of day Thursday.",
    channel: "phone",
    deliveryStatus: "read",
    createdAt: "2026-02-10T14:15:00Z",
  },
  {
    id: "com-6",
    conversationId: "conv-2",
    sender: "client",
    senderName: "James Ashworth",
    message: "Yes, G-LUXE. Manifest attached. Also add ground transport on the Newcastle side — two Range Rovers at the airport.",
    channel: "email",
    attachments: [
      {
        id: "att-1",
        name: "passenger_manifest_feb28.pdf",
        type: "application/pdf",
        size: 245000,
        url: "/attachments/att-1/passenger_manifest_feb28.pdf",
      },
    ],
    createdAt: "2026-02-11T09:00:00Z",
  },
  {
    id: "com-63",
    conversationId: "conv-2",
    sender: "system",
    senderName: "System",
    message: "Booking created for G650 Newcastle charter.",
    channel: "email",
    event: {
      type: "booking_created",
      bookingId: "bk-8",
      title: "G650 Newcastle",
      category: "jet",
      price: 83435,
    },
    createdAt: "2026-02-11T10:00:00Z",
  },
  {
    id: "com-64",
    conversationId: "conv-2",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "email",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-8",
      title: "G650 Newcastle",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-02-11T10:05:00Z",
  },
  {
    id: "com-65",
    conversationId: "conv-2",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £83,435.",
    channel: "email",
    event: {
      type: "invoice_created",
      invoiceId: "inv-2",
      invoiceTotal: 83435,
    },
    createdAt: "2026-02-12T09:00:00Z",
  },
  {
    id: "com-66",
    conversationId: "conv-2",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "email",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-2",
      invoiceTotal: 83435,
    },
    createdAt: "2026-02-12T09:05:00Z",
  },
  // Conversation conv-3 communications (Lady Beaumont helicopter - in_review)
  {
    id: "com-7",
    conversationId: "conv-3",
    sender: "client",
    senderName: "Lady Charlotte Beaumont",
    message: "Darling, I need a heli from Battersea to Goodwood on the 5th. The AW139 please, not the smaller one. And I'll need return around midnight.",
    channel: "whatsapp",
    createdAt: "2026-02-18T09:00:00Z",
  },
  {
    id: "com-8",
    conversationId: "conv-3",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Of course, Lady Beaumont. AW139 confirmed for March 5th. Departure from Battersea Heliport at 2:00 PM, return at midnight from Goodwood. Shall I arrange VIP paddock access as well?",
    channel: "whatsapp",
    deliveryStatus: "read",
    createdAt: "2026-02-18T09:20:00Z",
  },
  {
    id: "com-9",
    conversationId: "conv-3",
    sender: "client",
    senderName: "Lady Charlotte Beaumont",
    message: "Yes, full VIP paddock. And have them prepare the private suite. My usual table.",
    channel: "whatsapp",
    createdAt: "2026-02-18T09:25:00Z",
  },
  // Conversation conv-4 communications (Lady Beaumont wedding fleet - converted)
  {
    id: "com-10",
    conversationId: "conv-4",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Good news — all four white Phantoms are confirmed for the 20th. Floral arrangements by McQueens will be installed the morning of. Route has been surveyed and approved by the Metropolitan Police.",
    channel: "email",
    deliveryStatus: "read",
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "com-11",
    conversationId: "conv-4",
    sender: "client",
    senderName: "Lady Charlotte Beaumont",
    message: "Perfect. Make sure the ribbons match the exact shade of ivory from the sample I sent. Pantone 11-0604 TCX.",
    channel: "email",
    attachments: [
      {
        id: "att-2",
        name: "ribbon_color_sample.jpg",
        type: "image/jpeg",
        size: 1200000,
        url: "/attachments/att-2/ribbon_color_sample.jpg",
      },
    ],
    createdAt: "2026-01-10T14:00:00Z",
  },
  {
    id: "com-57",
    conversationId: "conv-4",
    sender: "system",
    senderName: "System",
    message: "Booking created for Phantom Fleet Wedding.",
    channel: "email",
    event: {
      type: "booking_created",
      bookingId: "bk-2",
      title: "Phantom Fleet Wedding",
      category: "car",
      price: 26180,
    },
    createdAt: "2026-01-10T15:00:00Z",
  },
  {
    id: "com-58",
    conversationId: "conv-4",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £26,180.",
    channel: "email",
    event: {
      type: "invoice_created",
      invoiceId: "inv-4",
      invoiceTotal: 26180,
    },
    createdAt: "2026-01-12T10:00:00Z",
  },
  {
    id: "com-59",
    conversationId: "conv-4",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "email",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-4",
      invoiceTotal: 26180,
    },
    createdAt: "2026-01-12T10:05:00Z",
  },
  {
    id: "com-60",
    conversationId: "conv-4",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "email",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-2",
      title: "Phantom Fleet Wedding",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-01-12T10:10:00Z",
  },
  {
    id: "com-12",
    conversationId: "conv-4",
    sender: "system",
    senderName: "System",
    message: "Booking completed. All 4 vehicles delivered on schedule. Client satisfaction: excellent.",
    channel: "email",
    event: {
      type: "payment_confirmed",
      bookingId: "bk-2",
      paymentAmount: 26180,
      paymentMethod: "bank_transfer",
      invoiceId: "inv-4",
    },
    createdAt: "2026-01-20T16:00:00Z",
  },
  {
    id: "com-61",
    conversationId: "conv-4",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to paid.",
    channel: "email",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-2",
      title: "Phantom Fleet Wedding",
      fromStatus: "awaiting_payment",
      toStatus: "paid",
    },
    createdAt: "2026-01-20T16:05:00Z",
  },
  {
    id: "com-62",
    conversationId: "conv-4",
    sender: "system",
    senderName: "System",
    message: "Booking completed.",
    channel: "email",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-2",
      title: "Phantom Fleet Wedding",
      fromStatus: "in_progress",
      toStatus: "completed",
    },
    createdAt: "2026-01-20T18:00:00Z",
  },
  // Conversation conv-5 communications (Sheikh yacht - awaiting_client)
  {
    id: "com-13",
    conversationId: "conv-5",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Sheikh Al-Fayed, we have identified three superyachts meeting your specifications for Cowes Week Regatta. The 88m 'Eclipse II' with prime harbour position is my top recommendation. Deck plans and crew profiles attached.",
    channel: "concierge",
    deliveryStatus: "read",
    attachments: [
      {
        id: "att-3",
        name: "eclipse_ii_deck_plans.pdf",
        type: "application/pdf",
        size: 5400000,
        url: "/attachments/att-3/eclipse_ii_deck_plans.pdf",
      },
      {
        id: "att-4",
        name: "crew_profiles.pdf",
        type: "application/pdf",
        size: 3200000,
        url: "/attachments/att-4/crew_profiles.pdf",
      },
    ],
    createdAt: "2026-02-05T10:00:00Z",
  },
  {
    id: "com-14",
    conversationId: "conv-5",
    sender: "client",
    senderName: "Sheikh Omar Al-Fayed",
    message: "Eclipse II looks acceptable. But I need the master suite reconfigured. My designer will send specifications. Also, the chef must be Michelin-starred — no exceptions.",
    channel: "concierge",
    createdAt: "2026-02-06T15:00:00Z",
  },
  {
    id: "com-15",
    conversationId: "conv-5",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Understood. We are awaiting the designer's specifications for the master suite. I have shortlisted three Michelin-starred chefs with experience on superyachts. Profiles will follow. ACTION NEEDED: Please have your designer send specs by February 25th to meet the refit deadline.",
    channel: "concierge",
    deliveryStatus: "delivered",
    createdAt: "2026-02-07T09:00:00Z",
  },
  // Conversation conv-7 communications (Isabelle car - in_review)
  {
    id: "com-16",
    conversationId: "conv-7",
    sender: "client",
    senderName: "Isabelle de Montfort",
    message: "Elena, I need the Flying Spur for all of Fashion Week. The driver must know every venue — I cannot be late to Burberry or Alexander McQueen.",
    channel: "email",
    createdAt: "2026-02-05T13:00:00Z",
  },
  {
    id: "com-17",
    conversationId: "conv-7",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Bonjour Madame de Montfort. Pierre will be your chauffeur — he drove you last season and knows every venue entrance and back route in London. The Flying Spur in Meteor finish is reserved. I'll share the full schedule once the show calendar is finalised.",
    channel: "email",
    deliveryStatus: "read",
    createdAt: "2026-02-05T14:30:00Z",
  },
  {
    id: "com-18",
    conversationId: "conv-7",
    sender: "client",
    senderName: "Isabelle de Montfort",
    message: "Parfait. Also arrange storage in the boot for garment bags — I'll be collecting pieces throughout the week.",
    channel: "whatsapp",
    createdAt: "2026-02-06T10:00:00Z",
  },
  {
    id: "com-73",
    conversationId: "conv-7",
    sender: "system",
    senderName: "System",
    message: "Booking created for Bentley Fashion Week.",
    channel: "whatsapp",
    event: {
      type: "booking_created",
      bookingId: "bk-9",
      title: "Bentley Fashion Week",
      category: "car",
      price: 23446.5,
    },
    createdAt: "2026-02-06T11:00:00Z",
  },
  {
    id: "com-74",
    conversationId: "conv-7",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £23,446.50.",
    channel: "whatsapp",
    event: {
      type: "invoice_created",
      invoiceId: "inv-6",
      invoiceTotal: 23446.5,
    },
    createdAt: "2026-02-07T09:00:00Z",
  },
  {
    id: "com-75",
    conversationId: "conv-7",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "whatsapp",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-6",
      invoiceTotal: 23446.5,
    },
    createdAt: "2026-02-07T09:05:00Z",
  },
  {
    id: "com-76",
    conversationId: "conv-7",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to scheduled.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-9",
      title: "Bentley Fashion Week",
      fromStatus: "paid",
      toStatus: "scheduled",
    },
    createdAt: "2026-02-20T10:00:00Z",
  },
  // Conversation conv-9 communications (Harrington Heathrow transfer - converted)
  {
    id: "com-94",
    conversationId: "conv-9",
    sender: "system",
    senderName: "System",
    message: "New request received from website.",
    channel: "web",
    event: {
      type: "web_form_submitted",
      title: "S-Class, Heathrow T5 to The Savoy",
    },
    createdAt: "2026-01-16T08:55:00Z",
  },
  {
    id: "com-19",
    conversationId: "conv-9",
    sender: "client",
    senderName: "Robert Harrington",
    message: "Booking S-Class for my Heathrow arrival on the 18th. Terminal 5, landing around 8 PM. Three large bags.",
    channel: "web",
    createdAt: "2026-01-16T09:00:00Z",
  },
  {
    id: "com-20",
    conversationId: "conv-9",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Confirmed, Mr. Harrington. Your driver will be waiting at Terminal 5 arrivals with a name board. S-Class with ample boot space for your luggage. ETA to The Savoy approximately 45 minutes depending on traffic.",
    channel: "web",
    deliveryStatus: "read",
    createdAt: "2026-01-16T09:30:00Z",
  },
  {
    id: "com-21",
    conversationId: "conv-9",
    sender: "system",
    senderName: "System",
    message: "Trip completed successfully. Duration: 48 minutes.",
    channel: "web",
    createdAt: "2026-01-18T21:30:00Z",
  },
  // Conversation conv-11 communications (Petrova Range Rover - in_review)
  {
    id: "com-22",
    conversationId: "conv-11",
    sender: "client",
    senderName: "Natasha Petrova",
    message: "Hi, I'd like a Range Rover from Claridge's to Soho Farmhouse next weekend. The Autobiography if possible — we had one last time and loved it.",
    channel: "phone",
    createdAt: "2026-02-20T11:00:00Z",
  },
  {
    id: "com-23",
    conversationId: "conv-11",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Hello Ms Petrova. The Range Rover Autobiography LWB is available for March 7-9. I'll arrange pickup at Claridge's main entrance at 9 AM. Would you like any refreshments stocked in the vehicle?",
    channel: "phone",
    deliveryStatus: "read",
    createdAt: "2026-02-20T11:20:00Z",
  },
  {
    id: "com-24",
    conversationId: "conv-11",
    sender: "client",
    senderName: "Natasha Petrova",
    message: "Still water and some light snacks would be lovely, thank you.",
    channel: "phone",
    createdAt: "2026-02-20T11:25:00Z",
  },
  // Conversation conv-14 communications (Mei Lin jet - in_review)
  {
    id: "com-25",
    conversationId: "conv-14",
    sender: "client",
    senderName: "Mei Lin Zhang",
    message: "Need Challenger 350 London to Manchester for March 12. Four passengers. Can you confirm the crew? Also, we have specific dietary requirements — no shellfish for two passengers.",
    channel: "whatsapp",
    createdAt: "2026-02-22T06:00:00Z",
  },
  {
    id: "com-26",
    conversationId: "conv-14",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Ms Zhang, I have a Challenger 350 confirmed. Departure 7 AM from Farnborough TAG Terminal. The caterer has been briefed on the no-shellfish requirement for two guests. I'll send the full flight brief by March 8.",
    channel: "whatsapp",
    deliveryStatus: "delivered",
    createdAt: "2026-02-22T08:00:00Z",
  },
  {
    id: "com-77",
    conversationId: "conv-14",
    sender: "system",
    senderName: "System",
    message: "Booking created for Challenger 350 Manchester.",
    channel: "whatsapp",
    event: {
      type: "booking_created",
      bookingId: "bk-14",
      title: "Challenger 350 Manchester",
      category: "jet",
      price: 51645,
    },
    createdAt: "2026-02-22T08:30:00Z",
  },
  // Conversation conv-15 communications (Mei Lin car - awaiting_client)
  {
    id: "com-27",
    conversationId: "conv-15",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Ms Zhang, the Maybach GLS 600 is reserved for March 13. We still need your meeting itinerary to plan the route and timing. Could you please share it at your earliest convenience?",
    channel: "email",
    deliveryStatus: "read",
    createdAt: "2026-02-21T10:00:00Z",
  },
  {
    id: "com-28",
    conversationId: "conv-15",
    sender: "client",
    senderName: "Mei Lin Zhang",
    message: "I'll have my assistant send the itinerary by end of this week. There will be at least 4 stops across the City and West End.",
    channel: "email",
    createdAt: "2026-02-22T03:00:00Z",
  },
  // Conversation conv-18 communications (Kensington fleet - in_review)
  {
    id: "com-29",
    conversationId: "conv-18",
    sender: "client",
    senderName: "Sarah Kensington",
    message: "We need three Phantoms for the charity gala at the V&A on March 2nd. Our celebrity guests require absolute discretion. Tinted windows mandatory. Can you coordinate with our PR team on arrival timing?",
    channel: "concierge",
    createdAt: "2026-02-12T10:00:00Z",
  },
  {
    id: "com-30",
    conversationId: "conv-18",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Absolutely, Ms Kensington. Three Phantoms with factory-tinted privacy glass confirmed. I'll need your PR team's contact to coordinate the 30-second interval arrivals at the red carpet. All drivers are NDA-cleared.",
    channel: "concierge",
    deliveryStatus: "read",
    createdAt: "2026-02-12T10:45:00Z",
  },
  {
    id: "com-31",
    conversationId: "conv-18",
    sender: "client",
    senderName: "Sarah Kensington",
    message: "Perfect. PR contact: jessica.hall@kensingtonpr.co.uk. She'll send the exact arrival schedule by February 28th. Each guest will have a personal assistant in the vehicle — please ensure rear seating for 3 in each car.",
    channel: "email",
    attachments: [
      {
        id: "att-5",
        name: "gala_event_brief.pdf",
        type: "application/pdf",
        size: 890000,
        url: "/attachments/att-5/gala_event_brief.pdf",
      },
    ],
    createdAt: "2026-02-13T09:00:00Z",
  },
  // Conversation conv-21 communications (Okafor Stansted - in_review)
  {
    id: "com-32",
    conversationId: "conv-21",
    sender: "client",
    senderName: "Amara Okafor",
    message: "I need the S-Class with meet and greet for March 3rd Stansted arrival. Please ensure the driver knows the route to The Gherkin.",
    channel: "whatsapp",
    createdAt: "2026-02-18T07:00:00Z",
  },
  {
    id: "com-33",
    conversationId: "conv-21",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Confirmed, Ms Okafor. S-Class arranged with meet and greet at Stansted arrivals. Route from Stansted to 30 St Mary Axe is approximately 60 minutes. Driver James is assigned and knows the City well.",
    channel: "whatsapp",
    deliveryStatus: "sent",
    createdAt: "2026-02-18T09:00:00Z",
  },
  // Conversation conv-23 communications (Ashworth yacht follow-up - awaiting_client)
  {
    id: "com-34",
    conversationId: "conv-23",
    sender: "client",
    senderName: "James Ashworth",
    message: "Marcus, regarding the Solent charter — I want the same captain from last year, Captain Morrison. Also add the Jet Ski package and the 40ft tender, not the 30ft. My children will be joining this time.",
    channel: "concierge",
    createdAt: "2026-02-15T08:00:00Z",
  },
  {
    id: "com-35",
    conversationId: "conv-23",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Mr. Ashworth, Captain Morrison is available and delighted to be aboard again. I'm working on upgrading the tender to the 40ft and adding the full water toys package including Jet Skis. For the children, shall I arrange the youth entertainment coordinator as well? I also need to know ages for safety equipment sizing.",
    channel: "concierge",
    deliveryStatus: "read",
    createdAt: "2026-02-15T10:00:00Z",
  },
  {
    id: "com-36",
    conversationId: "conv-23",
    sender: "client",
    senderName: "James Ashworth",
    message: "Ages 8 and 11. Yes to the entertainment coordinator. And my wife wants the spa to be fully operational — she was disappointed last time. Make sure the therapist is top-tier.",
    channel: "concierge",
    createdAt: "2026-02-16T14:00:00Z",
  },
  // Conversation conv-6 communications (Sheikh jet - new)
  {
    id: "com-37",
    conversationId: "conv-6",
    sender: "client",
    senderName: "Sheikh Omar Al-Fayed",
    message: "I require a BBJ for my delegation travelling to London from Manchester on March 15. Twenty passengers. The aircraft must have a full bedroom suite. Catering by Al Reef — they know my requirements.",
    channel: "phone",
    createdAt: "2026-02-24T11:00:00Z",
  },
  // Conversation conv-8 communications (Isabelle helicopter - converted)
  {
    id: "com-38",
    conversationId: "conv-8",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Mme de Montfort, your Lake District helicopter tour is confirmed for January 25th at 11 AM. Bollinger Rosé will be served during the flight. Landing at Windermere, and your table at L'Enclume is reserved for 1 PM.",
    channel: "whatsapp",
    deliveryStatus: "read",
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "com-39",
    conversationId: "conv-8",
    sender: "client",
    senderName: "Isabelle de Montfort",
    message: "Merci Marcus. Can you also arrange transport from Windermere back to London after lunch? Something comfortable — perhaps a Range Rover?",
    channel: "whatsapp",
    createdAt: "2026-01-20T11:00:00Z",
  },
  {
    id: "com-40",
    conversationId: "conv-8",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Of course! Range Rover Autobiography will be waiting at the restaurant. Driver is familiar with the M6 route back to London. Estimated drive time: 4 hours.",
    channel: "whatsapp",
    deliveryStatus: "read",
    createdAt: "2026-01-20T11:15:00Z",
  },
  {
    id: "com-67",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Booking created for Helicopter Lake District tour.",
    channel: "whatsapp",
    event: {
      type: "booking_created",
      bookingId: "bk-3",
      title: "Helicopter Lake District",
      category: "helicopter",
      price: 9240,
    },
    createdAt: "2026-01-20T11:30:00Z",
  },
  {
    id: "com-68",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £9,240.",
    channel: "whatsapp",
    event: {
      type: "invoice_created",
      invoiceId: "inv-3",
      invoiceTotal: 9240,
    },
    createdAt: "2026-01-21T09:00:00Z",
  },
  {
    id: "com-69",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "whatsapp",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-3",
      invoiceTotal: 9240,
    },
    createdAt: "2026-01-21T09:05:00Z",
  },
  {
    id: "com-70",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to scheduled.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-3",
      title: "Helicopter Lake District",
      fromStatus: "paid",
      toStatus: "scheduled",
    },
    createdAt: "2026-01-22T10:00:00Z",
  },
  {
    id: "com-71",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to in progress.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-3",
      title: "Helicopter Lake District",
      fromStatus: "scheduled",
      toStatus: "in_progress",
    },
    createdAt: "2026-01-25T11:00:00Z",
  },
  {
    id: "com-41",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Helicopter tour completed. Client rated experience 5/5. Ground transport completed without issues.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-3",
      title: "Lake District Helicopter Tour",
      fromStatus: "in_progress",
      toStatus: "completed",
    },
    createdAt: "2026-01-25T17:00:00Z",
  },
  {
    id: "com-72",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Payment confirmed.",
    channel: "whatsapp",
    event: {
      type: "payment_confirmed",
      bookingId: "bk-3",
      paymentAmount: 9240,
      paymentMethod: "card",
      invoiceId: "inv-3",
    },
    createdAt: "2026-02-18T10:00:00Z",
  },
  // Conversation conv-12 communications (Petrova cancelled jet)
  {
    id: "com-42",
    conversationId: "conv-12",
    sender: "client",
    senderName: "Natasha Petrova",
    message: "I need to cancel the Newquay flight. My schedule has changed completely. Apologies for the short notice.",
    channel: "email",
    createdAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "com-43",
    conversationId: "conv-12",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Understood, Ms Petrova. The Citation XLS booking has been cancelled. No cancellation fees apply as we are still outside the 48-hour window. We look forward to assisting you next time.",
    channel: "email",
    deliveryStatus: "read",
    createdAt: "2026-02-10T09:30:00Z",
  },
  // Conversation conv-13 communications (Whitfield Tesla - converted)
  {
    id: "com-44",
    conversationId: "conv-13",
    sender: "client",
    senderName: "Thomas Whitfield",
    message: "Booked via website: Tesla Model S Plaid from City Airport to my office at Canary Wharf. Arriving 3 PM on Jan 22. I prefer electric vehicles whenever available.",
    channel: "web",
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "com-45",
    conversationId: "conv-13",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Welcome, Mr Whitfield. Tesla Model S Plaid confirmed. We've noted your EV preference for future bookings. Driver will meet you at City Airport arrivals with a name board.",
    channel: "web",
    deliveryStatus: "read",
    createdAt: "2026-01-20T10:30:00Z",
  },
  // Conversation conv-16 communications (Mendes Gatwick - converted)
  {
    id: "com-46",
    conversationId: "conv-16",
    sender: "system",
    senderName: "System",
    message: "New request received from website.",
    channel: "web",
    event: {
      type: "web_form_submitted",
      title: "E-Class, Gatwick to The Grand Brighton",
    },
    createdAt: "2026-01-25T12:00:00Z",
  },
  {
    id: "com-47",
    conversationId: "conv-16",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Mr Mendes, your E-Class transfer is confirmed. Driver will be waiting at Gatwick South Terminal arrivals. He'll have a discreet LLC Car sign. Safe travels.",
    channel: "web",
    deliveryStatus: "read",
    createdAt: "2026-01-26T08:00:00Z",
  },
  // Conversation conv-19 communications (Kensington Heathrow - converted)
  {
    id: "com-48",
    conversationId: "conv-19",
    sender: "client",
    senderName: "Sarah Kensington",
    message: "Need an S-Class for my Heathrow arrival Feb 5. Terminal 5, BA flight arriving international. Going to The Connaught.",
    channel: "email",
    createdAt: "2026-02-03T09:00:00Z",
  },
  {
    id: "com-49",
    conversationId: "conv-19",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "All set, Ms Kensington. We'll be tracking your BA flight for any delays. Driver will be in the T5 arrivals hall. The Connaught is approximately 45 minutes from Heathrow at that hour.",
    channel: "email",
    deliveryStatus: "read",
    createdAt: "2026-02-03T09:45:00Z",
  },
  {
    id: "com-50",
    conversationId: "conv-19",
    sender: "system",
    senderName: "System",
    message: "BA flight arrived on time. Client picked up at 7:35 AM. Dropped off at The Connaught at 8:45 AM.",
    channel: "email",
    createdAt: "2026-02-05T08:45:00Z",
  },
  // Conversation conv-25 communications (Harrington Heathrow to City - completed, read)
  {
    id: "com-80",
    conversationId: "conv-25",
    sender: "client",
    senderName: "Robert Harrington",
    message: "Hi, I need an S-Class from Heathrow T2 to my office in the City on Feb 20. Landing at 2 PM.",
    channel: "web",
    createdAt: "2026-02-18T10:00:00Z",
  },
  {
    id: "com-81",
    conversationId: "conv-25",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Confirmed, Mr. Harrington. S-Class with meet and greet at Terminal 2. Driver will have a name board. ETA to Bishopsgate approximately 50 minutes.",
    channel: "web",
    deliveryStatus: "read",
    createdAt: "2026-02-18T10:30:00Z",
  },
  {
    id: "com-82",
    conversationId: "conv-25",
    sender: "system",
    senderName: "System",
    message: "Trip completed successfully. Duration: 47 minutes.",
    channel: "web",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-16",
      title: "S-Class Heathrow to City",
      fromStatus: "in_progress",
      toStatus: "completed",
    },
    createdAt: "2026-02-20T15:30:00Z",
  },
  {
    id: "com-92",
    conversationId: "conv-25",
    sender: "system",
    senderName: "Marcus Chen",
    channel: "web",
    message: "Conversation resolved",
    event: { type: "conversation_resolved" },
    createdAt: "2026-02-20T16:00:00Z",
  },
  // Conversation conv-26 communications (Whitfield Audi e-tron - scheduled, read)
  {
    id: "com-83",
    conversationId: "conv-26",
    sender: "client",
    senderName: "Thomas Whitfield",
    message: "I'd like to book an electric vehicle from Canary Wharf to Heathrow T5 on April 10. Early morning, around 6 AM pickup. Audi e-tron GT if available.",
    channel: "email",
    createdAt: "2026-02-25T09:00:00Z",
  },
  {
    id: "com-84",
    conversationId: "conv-26",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Good morning, Mr Whitfield. Audi e-tron GT confirmed for April 10 at 6 AM from One Canada Square. Your EV preference is noted. Flight details will help us monitor for any timing adjustments.",
    channel: "email",
    deliveryStatus: "read",
    createdAt: "2026-02-25T09:30:00Z",
  },
  {
    id: "com-85",
    conversationId: "conv-26",
    sender: "client",
    senderName: "Thomas Whitfield",
    message: "BA 117 to New York, departing 9:15 AM. Thanks for arranging.",
    channel: "email",
    createdAt: "2026-02-25T10:00:00Z",
  },
  // Conversation conv-27 communications (Mendes Oxford weekend - completed, read)
  {
    id: "com-86",
    conversationId: "conv-27",
    sender: "client",
    senderName: "Carlos Mendes",
    message: "Can I get a Range Rover Sport from The Langham to Oxford on Feb 15? Weekend trip, just the two of us.",
    channel: "phone",
    createdAt: "2026-02-12T08:00:00Z",
  },
  {
    id: "com-87",
    conversationId: "conv-27",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Of course, Mr Mendes. Range Rover Sport reserved for February 15 at 9 AM from The Langham. Drop-off at The Randolph Hotel in Oxford. Enjoy the weekend.",
    channel: "phone",
    deliveryStatus: "read",
    createdAt: "2026-02-12T08:30:00Z",
  },
  {
    id: "com-88",
    conversationId: "conv-27",
    sender: "system",
    senderName: "System",
    message: "Trip completed. Duration: 1 hour 35 minutes. No issues.",
    channel: "phone",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-17",
      title: "Range Rover Oxford Weekend",
      fromStatus: "in_progress",
      toStatus: "completed",
    },
    createdAt: "2026-02-16T18:00:00Z",
  },
  {
    id: "com-93",
    conversationId: "conv-27",
    sender: "system",
    senderName: "Marcus Chen",
    channel: "phone",
    message: "Conversation resolved",
    event: { type: "conversation_resolved" },
    createdAt: "2026-02-16T19:00:00Z",
  },
  // Conversation conv-28 communications (Blake Gatwick to Surrey - scheduled, read)
  {
    id: "com-89",
    conversationId: "conv-28",
    sender: "client",
    senderName: "Jonathan Blake",
    message: "Booking request: E-Class from Gatwick North Terminal to Virginia Water on April 15. Evening arrival around 7 PM.",
    channel: "web",
    createdAt: "2026-02-24T14:00:00Z",
  },
  {
    id: "com-90",
    conversationId: "conv-28",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Confirmed, Mr Blake. Mercedes E-Class will be waiting at Gatwick North Terminal arrivals. Route to Virginia Water is approximately 40 minutes. Please share your flight details when available.",
    channel: "web",
    deliveryStatus: "read",
    createdAt: "2026-02-24T14:30:00Z",
  },
  {
    id: "com-91",
    conversationId: "conv-28",
    sender: "client",
    senderName: "Jonathan Blake",
    message: "EasyJet EZY8471 from Geneva, landing 6:50 PM. Thanks.",
    channel: "web",
    createdAt: "2026-02-24T15:00:00Z",
  },
  // Conversation conv-10 communications (Harrington corporate shuttle)
  {
    id: "com-95",
    conversationId: "conv-10",
    sender: "system",
    senderName: "System",
    message: "New request received via email.",
    channel: "email",
    event: {
      type: "web_form_submitted",
      title: "Executive Van, The Langham to ExCeL London",
    },
    createdAt: "2026-02-25T13:55:00Z",
  },
  {
    id: "com-96",
    conversationId: "conv-10",
    sender: "client",
    senderName: "Robert Harrington",
    message: "Hi, I need a Mercedes V-Class for a corporate event shuttle on March 10. Pickup from The Langham at 7 AM, then back and forth to ExCeL London all day. 8-hour booking.",
    channel: "email",
    createdAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "com-97",
    conversationId: "conv-10",
    sender: "agent",
    senderName: "Elena Vasquez",
    message: "Good afternoon, Mr Harrington. Mercedes V-Class is available for March 10. I'll arrange an 8-hour shuttle service between The Langham and ExCeL London starting at 7 AM. Shall I include refreshments for the vehicle?",
    channel: "email",
    deliveryStatus: "delivered",
    createdAt: "2026-02-25T14:30:00Z",
  },
  // Conversation conv-17 communications (Carlos Mendes helicopter — unassigned)
  {
    id: "com-98",
    conversationId: "conv-17",
    sender: "client",
    senderName: "Carlos Mendes",
    message: "Hi, I'd like to book a helicopter transfer from Battersea Heliport to the Isle of Wight on March 20. Party of 3 for a weekend trip. Can you arrange this?",
    channel: "phone",
    createdAt: "2026-02-26T08:00:00Z",
  },
  // Conversation conv-22 communications (Okafor Hawker 800 — unassigned)
  {
    id: "com-99",
    conversationId: "conv-22",
    sender: "client",
    senderName: "Amara Okafor",
    message: "I need a Hawker 800XP for a same-day round trip from Farnborough to Birmingham on March 10. Six passengers, morning departure for a business meeting. Please advise on availability.",
    channel: "phone",
    createdAt: "2026-02-26T10:00:00Z",
  },
  // Conversation conv-24 communications (Sheikh cancelled Bentley)
  {
    id: "com-100",
    conversationId: "conv-24",
    sender: "client",
    senderName: "Sheikh Omar Al-Fayed",
    message: "I would like a Bentley Bentayga with driver for a London sightseeing tour on February 10. Pick up from The Ritz at 9 AM. 6-hour booking, ending at Kensington Palace.",
    channel: "email",
    createdAt: "2026-01-30T14:00:00Z",
  },
  {
    id: "com-101",
    conversationId: "conv-24",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Of course, Sheikh Al-Fayed. Bentley Bentayga confirmed for February 10 from The Ritz. The route will include key London landmarks. Driver Khalid is assigned — he is familiar with your preferences.",
    channel: "email",
    deliveryStatus: "read",
    createdAt: "2026-01-30T15:00:00Z",
  },
  {
    id: "com-102",
    conversationId: "conv-24",
    sender: "client",
    senderName: "Sheikh Omar Al-Fayed",
    message: "Marcus, I need to cancel the London sightseeing booking. My travel plans have changed and I will not be in London on that date.",
    channel: "email",
    createdAt: "2026-02-07T14:00:00Z",
  },
  {
    id: "com-103",
    conversationId: "conv-24",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Understood, Sheikh Al-Fayed. The Bentley Bentayga booking for February 10 has been cancelled. No cancellation charges apply. Please let us know when you'd like to rearrange.",
    channel: "email",
    deliveryStatus: "read",
    createdAt: "2026-02-07T15:00:00Z",
  },
  // ──────────────────────────────────────────────────────────
  // Missing service messages (com-104 → com-150)
  // ──────────────────────────────────────────────────────────

  // conv-14: Mei Lin Zhang — missing invoice_created
  {
    id: "com-104",
    conversationId: "conv-14",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £51,645.",
    channel: "whatsapp",
    event: {
      type: "invoice_created",
      invoiceId: "inv-5",
      invoiceTotal: 51645,
    },
    createdAt: "2026-02-23T09:00:00Z",
  },

  // conv-7: Isabelle de Montfort — missing draft→awaiting_payment, payment_confirmed, awaiting_payment→paid
  {
    id: "com-105",
    conversationId: "conv-7",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-9",
      title: "Bentley Fashion Week",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-02-07T09:10:00Z",
  },
  {
    id: "com-106",
    conversationId: "conv-7",
    sender: "system",
    senderName: "System",
    message: "Payment confirmed.",
    channel: "whatsapp",
    event: {
      type: "payment_confirmed",
      bookingId: "bk-9",
      paymentAmount: 23446.5,
      paymentMethod: "bank_transfer",
      invoiceId: "inv-6",
    },
    createdAt: "2026-02-20T09:50:00Z",
  },
  {
    id: "com-107",
    conversationId: "conv-7",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to paid.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-9",
      title: "Bentley Fashion Week",
      fromStatus: "awaiting_payment",
      toStatus: "paid",
    },
    createdAt: "2026-02-20T09:55:00Z",
  },

  // conv-11: Natasha Petrova — missing booking_created, invoice_created, invoice_sent, draft→awaiting_payment
  {
    id: "com-108",
    conversationId: "conv-11",
    sender: "system",
    senderName: "System",
    message: "Booking created for Range Rover Cotswolds.",
    channel: "phone",
    event: {
      type: "booking_created",
      bookingId: "bk-10",
      title: "Range Rover Cotswolds",
      category: "car",
      price: 5318.5,
    },
    createdAt: "2026-02-21T10:00:00Z",
  },
  {
    id: "com-109",
    conversationId: "conv-11",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £5,318.50.",
    channel: "phone",
    event: {
      type: "invoice_created",
      invoiceId: "inv-9",
      invoiceTotal: 5318.5,
    },
    createdAt: "2026-02-21T10:05:00Z",
  },
  {
    id: "com-110",
    conversationId: "conv-11",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "phone",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-9",
      invoiceTotal: 5318.5,
    },
    createdAt: "2026-02-21T10:10:00Z",
  },
  {
    id: "com-111",
    conversationId: "conv-11",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "phone",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-10",
      title: "Range Rover Cotswolds",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-02-21T10:15:00Z",
  },

  // conv-18: Sarah Kensington — missing full lifecycle (booking_created → scheduled)
  {
    id: "com-112",
    conversationId: "conv-18",
    sender: "system",
    senderName: "System",
    message: "Booking created for Phantom Fleet V&A Gala.",
    channel: "concierge",
    event: {
      type: "booking_created",
      bookingId: "bk-11",
      title: "Phantom Fleet V&A Gala",
      category: "car",
      price: 20350,
    },
    createdAt: "2026-02-14T09:00:00Z",
  },
  {
    id: "com-113",
    conversationId: "conv-18",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £20,350.",
    channel: "concierge",
    event: {
      type: "invoice_created",
      invoiceId: "inv-13",
      invoiceTotal: 20350,
    },
    createdAt: "2026-02-14T09:05:00Z",
  },
  {
    id: "com-114",
    conversationId: "conv-18",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "concierge",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-13",
      invoiceTotal: 20350,
    },
    createdAt: "2026-02-14T09:10:00Z",
  },
  {
    id: "com-115",
    conversationId: "conv-18",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "concierge",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-11",
      title: "Phantom Fleet V&A Gala",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-02-14T09:15:00Z",
  },
  {
    id: "com-116",
    conversationId: "conv-18",
    sender: "system",
    senderName: "System",
    message: "Payment confirmed.",
    channel: "concierge",
    event: {
      type: "payment_confirmed",
      bookingId: "bk-11",
      paymentAmount: 20350,
      paymentMethod: "card",
      invoiceId: "inv-13",
    },
    createdAt: "2026-02-25T15:00:00Z",
  },
  {
    id: "com-117",
    conversationId: "conv-18",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to paid.",
    channel: "concierge",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-11",
      title: "Phantom Fleet V&A Gala",
      fromStatus: "awaiting_payment",
      toStatus: "paid",
    },
    createdAt: "2026-02-25T15:05:00Z",
  },
  {
    id: "com-118",
    conversationId: "conv-18",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to scheduled.",
    channel: "concierge",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-11",
      title: "Phantom Fleet V&A Gala",
      fromStatus: "paid",
      toStatus: "scheduled",
    },
    createdAt: "2026-02-25T15:10:00Z",
  },

  // conv-21: Amara Okafor — missing booking_created, invoice_created, invoice_sent, draft→awaiting_payment
  {
    id: "com-119",
    conversationId: "conv-21",
    sender: "system",
    senderName: "System",
    message: "Booking created for S-Class Stansted to City.",
    channel: "whatsapp",
    event: {
      type: "booking_created",
      bookingId: "bk-12",
      title: "S-Class Stansted to City",
      category: "car",
      price: 8250,
    },
    createdAt: "2026-02-19T10:00:00Z",
  },
  {
    id: "com-120",
    conversationId: "conv-21",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £8,250.",
    channel: "whatsapp",
    event: {
      type: "invoice_created",
      invoiceId: "inv-15",
      invoiceTotal: 8250,
    },
    createdAt: "2026-02-19T10:05:00Z",
  },
  {
    id: "com-121",
    conversationId: "conv-21",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "whatsapp",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-15",
      invoiceTotal: 8250,
    },
    createdAt: "2026-02-19T10:10:00Z",
  },
  {
    id: "com-122",
    conversationId: "conv-21",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-12",
      title: "S-Class Stansted to City",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-02-19T10:15:00Z",
  },

  // conv-28: Jonathan Blake — missing booking_created, invoice_created, invoice_sent, draft→awaiting_payment
  {
    id: "com-123",
    conversationId: "conv-28",
    sender: "system",
    senderName: "System",
    message: "Booking created for E-Class Gatwick to Surrey.",
    channel: "web",
    event: {
      type: "booking_created",
      bookingId: "bk-19",
      title: "E-Class Gatwick to Surrey",
      category: "car",
      price: 418,
    },
    createdAt: "2026-02-24T15:30:00Z",
  },
  {
    id: "com-124",
    conversationId: "conv-28",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £418.",
    channel: "web",
    event: {
      type: "invoice_created",
      invoiceId: "inv-19",
      invoiceTotal: 418,
    },
    createdAt: "2026-02-25T11:00:00Z",
  },
  {
    id: "com-125",
    conversationId: "conv-28",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "web",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-19",
      invoiceTotal: 418,
    },
    createdAt: "2026-02-25T11:05:00Z",
  },
  {
    id: "com-126",
    conversationId: "conv-28",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "web",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-19",
      title: "E-Class Gatwick to Surrey",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-02-25T11:10:00Z",
  },

  // conv-10: Robert Harrington — missing booking_created
  {
    id: "com-127",
    conversationId: "conv-10",
    sender: "system",
    senderName: "System",
    message: "Booking created for Executive Van ExCeL Shuttle.",
    channel: "email",
    event: {
      type: "booking_created",
      bookingId: "bk-20",
      title: "Executive Van ExCeL Shuttle",
      category: "car",
      price: 1250,
    },
    createdAt: "2026-02-25T15:00:00Z",
  },

  // conv-20: Jonathan Blake — missing client/agent msgs + full lifecycle
  {
    id: "com-128",
    conversationId: "conv-20",
    sender: "client",
    senderName: "Jonathan Blake",
    message: "Hi, I'd like to book a BMW 7 Series from Heathrow Terminal 4 to Virginia Water on March 8. Evening arrival, around 9 PM.",
    channel: "web",
    createdAt: "2026-02-24T16:00:00Z",
  },
  {
    id: "com-129",
    conversationId: "conv-20",
    sender: "agent",
    senderName: "Marcus Chen",
    message: "Confirmed, Mr Blake. BMW 7 Series reserved for March 8 at Terminal 4. Driver will be waiting in arrivals. Route to Virginia Water is approximately 40 minutes at that hour.",
    channel: "web",
    deliveryStatus: "read",
    createdAt: "2026-02-24T17:00:00Z",
  },
  {
    id: "com-130",
    conversationId: "conv-20",
    sender: "system",
    senderName: "System",
    message: "Booking created for BMW 7 Series Heathrow to Surrey.",
    channel: "web",
    event: {
      type: "booking_created",
      bookingId: "bk-15",
      title: "BMW 7 Series Heathrow to Surrey",
      category: "car",
      price: 709.5,
    },
    createdAt: "2026-02-25T10:00:00Z",
  },
  {
    id: "com-131",
    conversationId: "conv-20",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £709.50.",
    channel: "web",
    event: {
      type: "invoice_created",
      invoiceId: "inv-18",
      invoiceTotal: 709.5,
    },
    createdAt: "2026-02-25T10:05:00Z",
  },
  {
    id: "com-132",
    conversationId: "conv-20",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "web",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-18",
      invoiceTotal: 709.5,
    },
    createdAt: "2026-02-25T10:10:00Z",
  },
  {
    id: "com-133",
    conversationId: "conv-20",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "web",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-15",
      title: "BMW 7 Series Heathrow to Surrey",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-02-25T10:15:00Z",
  },

  // conv-26: Thomas Whitfield — missing full lifecycle (booking_created → scheduled)
  {
    id: "com-134",
    conversationId: "conv-26",
    sender: "system",
    senderName: "System",
    message: "Booking created for Audi e-tron GT Heathrow.",
    channel: "email",
    event: {
      type: "booking_created",
      bookingId: "bk-18",
      title: "Audi e-tron GT Heathrow",
      category: "car",
      price: 550,
    },
    createdAt: "2026-02-25T10:30:00Z",
  },
  {
    id: "com-135",
    conversationId: "conv-26",
    sender: "system",
    senderName: "System",
    message: "Invoice created for £550.",
    channel: "email",
    event: {
      type: "invoice_created",
      invoiceId: "inv-20",
      invoiceTotal: 550,
    },
    createdAt: "2026-02-25T11:00:00Z",
  },
  {
    id: "com-136",
    conversationId: "conv-26",
    sender: "system",
    senderName: "System",
    message: "Invoice sent to client.",
    channel: "email",
    event: {
      type: "invoice_sent",
      invoiceId: "inv-20",
      invoiceTotal: 550,
    },
    createdAt: "2026-02-25T11:05:00Z",
  },
  {
    id: "com-137",
    conversationId: "conv-26",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "email",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-18",
      title: "Audi e-tron GT Heathrow",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-02-25T11:10:00Z",
  },
  {
    id: "com-138",
    conversationId: "conv-26",
    sender: "system",
    senderName: "System",
    message: "Payment confirmed.",
    channel: "email",
    event: {
      type: "payment_confirmed",
      bookingId: "bk-18",
      paymentAmount: 550,
      paymentMethod: "card",
      invoiceId: "inv-20",
    },
    createdAt: "2026-02-26T10:00:00Z",
  },
  {
    id: "com-139",
    conversationId: "conv-26",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to paid.",
    channel: "email",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-18",
      title: "Audi e-tron GT Heathrow",
      fromStatus: "awaiting_payment",
      toStatus: "paid",
    },
    createdAt: "2026-02-26T10:05:00Z",
  },
  {
    id: "com-140",
    conversationId: "conv-26",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to scheduled.",
    channel: "email",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-18",
      title: "Audi e-tron GT Heathrow",
      fromStatus: "paid",
      toStatus: "scheduled",
    },
    createdAt: "2026-02-26T11:00:00Z",
  },

  // conv-17: Carlos Mendes — missing booking_created
  {
    id: "com-141",
    conversationId: "conv-17",
    sender: "system",
    senderName: "System",
    message: "Booking created for Helicopter Isle of Wight.",
    channel: "phone",
    event: {
      type: "booking_created",
      bookingId: "bk-21",
      title: "Helicopter Isle of Wight",
      category: "helicopter",
      price: 4800,
    },
    createdAt: "2026-02-26T09:00:00Z",
  },

  // conv-22: Amara Okafor — missing booking_created
  {
    id: "com-142",
    conversationId: "conv-22",
    sender: "system",
    senderName: "System",
    message: "Booking created for Hawker 800XP Birmingham.",
    channel: "phone",
    event: {
      type: "booking_created",
      bookingId: "bk-22",
      title: "Hawker 800XP Birmingham",
      category: "jet",
      price: 18500,
    },
    createdAt: "2026-02-26T11:00:00Z",
  },

  // ── Completed/resolved conversations ──

  // conv-25: Robert Harrington — missing booking_created for bk-16
  {
    id: "com-143",
    conversationId: "conv-25",
    sender: "system",
    senderName: "System",
    message: "Booking created for S-Class Heathrow to City.",
    channel: "web",
    event: {
      type: "booking_created",
      bookingId: "bk-16",
      title: "S-Class Heathrow to City",
      category: "car",
      price: 585,
    },
    createdAt: "2026-02-18T11:00:00Z",
  },

  // conv-27: Carlos Mendes — missing booking_created for bk-17
  {
    id: "com-144",
    conversationId: "conv-27",
    sender: "system",
    senderName: "System",
    message: "Booking created for Range Rover Oxford Weekend.",
    channel: "phone",
    event: {
      type: "booking_created",
      bookingId: "bk-17",
      title: "Range Rover Oxford Weekend",
      category: "car",
      price: 1320,
    },
    createdAt: "2026-02-12T09:00:00Z",
  },

  // conv-9: Robert Harrington — missing booking_created for bk-4
  {
    id: "com-145",
    conversationId: "conv-9",
    sender: "system",
    senderName: "System",
    message: "Booking created for S-Class Heathrow to Savoy.",
    channel: "web",
    event: {
      type: "booking_created",
      bookingId: "bk-4",
      title: "S-Class Heathrow to Savoy",
      category: "car",
      price: 610.5,
    },
    createdAt: "2026-01-16T10:00:00Z",
  },

  // conv-13: Thomas Whitfield — missing booking_created for bk-5
  {
    id: "com-146",
    conversationId: "conv-13",
    sender: "system",
    senderName: "System",
    message: "Booking created for Tesla City Airport to Canary Wharf.",
    channel: "web",
    event: {
      type: "booking_created",
      bookingId: "bk-5",
      title: "Tesla City Airport to Canary Wharf",
      category: "car",
      price: 500.5,
    },
    createdAt: "2026-01-20T11:00:00Z",
  },

  // conv-16: Carlos Mendes — missing booking_created for bk-6
  {
    id: "com-147",
    conversationId: "conv-16",
    sender: "system",
    senderName: "System",
    message: "Booking created for E-Class Gatwick to Brighton.",
    channel: "web",
    event: {
      type: "booking_created",
      bookingId: "bk-6",
      title: "E-Class Gatwick to Brighton",
      category: "car",
      price: 445.5,
    },
    createdAt: "2026-01-25T13:00:00Z",
  },

  // conv-19: Sarah Kensington — missing booking_created for bk-7
  {
    id: "com-148",
    conversationId: "conv-19",
    sender: "system",
    senderName: "System",
    message: "Booking created for S-Class Heathrow to Connaught.",
    channel: "email",
    event: {
      type: "booking_created",
      bookingId: "bk-7",
      title: "S-Class Heathrow to Connaught",
      category: "car",
      price: 473,
    },
    createdAt: "2026-02-03T10:00:00Z",
  },

  // conv-8: Isabelle de Montfort — missing draft→awaiting_payment + awaiting_payment→paid for bk-3
  {
    id: "com-149",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to awaiting payment.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-3",
      title: "Helicopter Lake District",
      fromStatus: "draft",
      toStatus: "awaiting_payment",
    },
    createdAt: "2026-01-21T09:10:00Z",
  },
  {
    id: "com-150",
    conversationId: "conv-8",
    sender: "system",
    senderName: "System",
    message: "Booking status changed to paid.",
    channel: "whatsapp",
    event: {
      type: "booking_status_changed",
      bookingId: "bk-3",
      title: "Helicopter Lake District",
      fromStatus: "awaiting_payment",
      toStatus: "paid",
    },
    createdAt: "2026-01-22T09:55:00Z",
  },
];
