import type { Conversation } from "@/types";

export const conversations: Conversation[] = [
  // VIP client conversations (cli-1 through cli-4)
  {
    id: "conv-1",
    clientId: "cli-1",
    status: "converted",
    priority: "critical",
    channel: "concierge",
    serviceType: "car",
    title: "Airport Transfer - Farnborough to Mayfair Residence",
    description: "Mr. Ashworth requires a Mercedes-Maybach S680 transfer from Farnborough Airport to his Mayfair residence. Chilled Krug Grande Cuvée must be stocked. Driver must be pre-approved by security team.",
    pickupLocation: "Farnborough Airport (FAB), TAG Terminal",
    dropoffLocation: "Grosvenor Square, Mayfair, London W1K",
    pickupDate: "2026-01-15T18:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-01-15T16:00:00Z",
    createdAt: "2026-01-14T10:00:00Z",
    updatedAt: "2026-01-15T19:30:00Z",
  },
  {
    id: "conv-2",
    clientId: "cli-1",
    status: "in_review",
    priority: "high",
    channel: "phone",
    serviceType: "jet",
    title: "Gulfstream G650 Charter - London to Newcastle",
    description: "Weekend break. Gulfstream G650 or equivalent. Party of 6 with extensive luggage. Catering from The Dorchester required onboard.",
    pickupLocation: "Farnborough Airport (FAB), TAG Terminal",
    dropoffLocation: "Newcastle Airport (NCL), Private Terminal",
    pickupDate: "2026-02-28T08:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-27T20:00:00Z",
    createdAt: "2026-02-10T14:00:00Z",
    updatedAt: "2026-02-20T11:30:00Z",
  },
  {
    id: "conv-3",
    clientId: "cli-2",
    status: "in_review",
    priority: "critical",
    channel: "whatsapp",
    serviceType: "helicopter",
    title: "Helicopter Transfer - Battersea to Goodwood",
    description: "Lady Beaumont requires helicopter transfer for race day at Goodwood. AgustaWestland AW139 preferred. Landing at Goodwood Aerodrome. Return same evening.",
    pickupLocation: "Battersea Heliport, London SW11",
    dropoffLocation: "Goodwood Aerodrome, Chichester, West Sussex",
    pickupDate: "2026-03-05T14:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-03-04T10:00:00Z",
    createdAt: "2026-02-18T09:00:00Z",
    updatedAt: "2026-02-19T15:20:00Z",
  },
  {
    id: "conv-4",
    clientId: "cli-2",
    status: "converted",
    priority: "high",
    channel: "email",
    serviceType: "car",
    title: "Rolls-Royce Phantom Fleet - Wedding Convoy",
    description: "Fleet of 4 Rolls-Royce Phantoms for wedding party. White exteriors only. Floral arrangements by McQueens. Route from Claridge's to St Paul's Cathedral.",
    pickupLocation: "Claridge's, Brook Street, Mayfair, London W1K",
    dropoffLocation: "St Paul's Cathedral, London EC4M",
    pickupDate: "2026-01-20T10:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-01-19T12:00:00Z",
    createdAt: "2025-12-15T08:00:00Z",
    updatedAt: "2026-01-20T16:00:00Z",
  },
  {
    id: "conv-5",
    clientId: "cli-3",
    status: "awaiting_client",
    priority: "critical",
    channel: "concierge",
    serviceType: "yacht",
    title: "Superyacht Charter - Cowes Week Regatta, Isle of Wight",
    description: "80m+ superyacht for Cowes Week Regatta. 12 guests. Must have prime harbour position. Chef, crew, and entertainment to be arranged separately. Tender service required.",
    pickupLocation: "Cowes Harbour, Isle of Wight",
    dropoffLocation: "Cowes Harbour, Isle of Wight",
    pickupDate: "2026-05-22T12:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-25T18:00:00Z",
    createdAt: "2026-02-01T07:00:00Z",
    updatedAt: "2026-02-24T16:30:00Z",
  },
  {
    id: "conv-6",
    clientId: "cli-3",
    status: "new",
    priority: "high",
    channel: "phone",
    serviceType: "jet",
    title: "BBJ 737 Charter - Manchester to London",
    description: "Boeing Business Jet for entourage of 20. Full bedroom suite required. Halal catering from specified provider. Landing at Farnborough.",
    pickupLocation: "Manchester Airport (MAN), Private Terminal",
    dropoffLocation: "Farnborough Airport (FAB), TAG Terminal",
    pickupDate: "2026-03-15T06:00:00Z",
    assigneeId: null,
    slaDueAt: "2026-02-28T12:00:00Z",
    createdAt: "2026-02-24T11:00:00Z",
    updatedAt: "2026-02-24T11:00:00Z",
  },
  {
    id: "conv-7",
    clientId: "cli-4",
    status: "in_review",
    priority: "high",
    channel: "email",
    serviceType: "car",
    title: "Bentley Flying Spur - London Fashion Week",
    description: "Bentley Flying Spur with dedicated chauffeur for full Fashion Week schedule. 7-day rental. Must accommodate tight schedule changes. Driver fluent in French and English.",
    pickupLocation: "The Connaught, Carlos Place, Mayfair, London W1K",
    dropoffLocation: "Various Fashion Week venues, London",
    pickupDate: "2026-03-01T08:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-02-28T18:00:00Z",
    createdAt: "2026-02-05T13:00:00Z",
    updatedAt: "2026-02-22T10:00:00Z",
  },
  {
    id: "conv-8",
    clientId: "cli-4",
    status: "converted",
    priority: "medium",
    channel: "whatsapp",
    serviceType: "helicopter",
    title: "Helicopter Tour - Lake District",
    description: "Scenic helicopter tour around the Lake District for Mme de Montfort and 3 guests. Champagne service. Landing at Windermere for lunch at L'Enclume.",
    pickupLocation: "Battersea Heliport, London SW11",
    dropoffLocation: "Windermere, Lake District",
    pickupDate: "2026-01-25T11:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-01-24T14:00:00Z",
    createdAt: "2026-01-10T16:00:00Z",
    updatedAt: "2026-01-25T17:00:00Z",
  },
  // Non-VIP client conversations
  {
    id: "conv-9",
    clientId: "cli-5",
    status: "converted",
    priority: "medium",
    channel: "web",
    serviceType: "car",
    title: "S-Class Transfer - Heathrow to The Savoy",
    description: "Mercedes S-Class transfer from Heathrow Terminal 5. Meet and greet service. Luggage assistance for 3 bags.",
    pickupLocation: "London Heathrow Airport (LHR), Terminal 5",
    dropoffLocation: "The Savoy, Strand, London WC2R",
    pickupDate: "2026-01-18T20:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-01-18T18:00:00Z",
    createdAt: "2026-01-16T09:00:00Z",
    updatedAt: "2026-01-18T21:30:00Z",
  },
  {
    id: "conv-10",
    clientId: "cli-5",
    status: "new",
    priority: "low",
    channel: "email",
    serviceType: "car",
    title: "Executive Van - Corporate Event Shuttle",
    description: "Mercedes V-Class for corporate event. Shuttle service between hotel and ExCeL London. 8-hour booking.",
    pickupLocation: "The Langham, Portland Place, London W1B",
    dropoffLocation: "ExCeL London, Royal Victoria Dock, London E16",
    pickupDate: "2026-03-10T07:00:00Z",
    assigneeId: null,
    slaDueAt: "2026-03-08T12:00:00Z",
    createdAt: "2026-02-25T14:00:00Z",
    updatedAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "conv-11",
    clientId: "cli-6",
    status: "in_review",
    priority: "medium",
    channel: "phone",
    serviceType: "car",
    title: "Range Rover Autobiography - London to Cotswolds",
    description: "Range Rover Autobiography LWB for weekend countryside trip. Pick up from Claridge's. Return Sunday evening.",
    pickupLocation: "Claridge's, Brook Street, Mayfair, London W1K",
    dropoffLocation: "Soho Farmhouse, Great Tew, Oxfordshire OX7",
    pickupDate: "2026-03-07T09:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-03-06T12:00:00Z",
    createdAt: "2026-02-20T11:00:00Z",
    updatedAt: "2026-02-23T09:15:00Z",
  },
  {
    id: "conv-12",
    clientId: "cli-6",
    status: "closed",
    priority: "low",
    channel: "email",
    serviceType: "jet",
    title: "Citation XLS - London to Newquay (Cancelled)",
    description: "Originally requested Citation XLS charter to Cornwall. Client cancelled due to schedule change.",
    pickupLocation: "London Luton Airport (LTN), Signature FBO",
    dropoffLocation: "Cornwall Airport Newquay (NQY), Private Terminal",
    pickupDate: "2026-02-14T10:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-13T08:00:00Z",
    createdAt: "2026-02-01T16:00:00Z",
    updatedAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "conv-13",
    clientId: "cli-7",
    status: "converted",
    priority: "medium",
    channel: "web",
    serviceType: "car",
    title: "Tesla Model S Plaid - City Airport to Canary Wharf",
    description: "Tesla Model S Plaid from London City Airport to Canary Wharf office. Client prefers electric vehicles. Standard meet and greet.",
    pickupLocation: "London City Airport (LCY), Arrivals",
    dropoffLocation: "One Canada Square, Canary Wharf, London E14",
    pickupDate: "2026-01-22T15:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-01-22T13:00:00Z",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-01-22T16:30:00Z",
  },
  {
    id: "conv-14",
    clientId: "cli-8",
    status: "in_review",
    priority: "high",
    channel: "whatsapp",
    serviceType: "jet",
    title: "Challenger 350 - London to Manchester",
    description: "Bombardier Challenger 350 for business trip. Party of 4. Specific catering requirements to follow.",
    pickupLocation: "Farnborough Airport (FAB), TAG Terminal",
    dropoffLocation: "Manchester Airport (MAN), Private Terminal",
    pickupDate: "2026-03-12T07:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-03-10T12:00:00Z",
    createdAt: "2026-02-22T06:00:00Z",
    updatedAt: "2026-02-23T14:00:00Z",
  },
  {
    id: "conv-15",
    clientId: "cli-8",
    status: "awaiting_client",
    priority: "medium",
    channel: "email",
    serviceType: "car",
    title: "Maybach GLS 600 - London Full-Day Service",
    description: "Maybach GLS 600 with driver for full day in London. Client needs vehicle for multiple business meetings. Awaiting exact itinerary.",
    pickupLocation: "The Dorchester, Park Lane, London W1K",
    dropoffLocation: "Various locations, Central London",
    pickupDate: "2026-03-13T08:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-02-26T10:00:00Z",
    createdAt: "2026-02-21T08:00:00Z",
    updatedAt: "2026-02-24T11:00:00Z",
  },
  {
    id: "conv-16",
    clientId: "cli-9",
    status: "converted",
    priority: "low",
    channel: "web",
    serviceType: "car",
    title: "E-Class Transfer - Gatwick to Brighton",
    description: "Mercedes E-Class from Gatwick Airport to Brighton hotel.",
    pickupLocation: "London Gatwick Airport (LGW), South Terminal",
    dropoffLocation: "The Grand Brighton, King's Road, Brighton BN1",
    pickupDate: "2026-01-28T22:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-01-28T20:00:00Z",
    createdAt: "2026-01-25T12:00:00Z",
    updatedAt: "2026-01-28T23:15:00Z",
  },
  {
    id: "conv-17",
    clientId: "cli-9",
    status: "new",
    priority: "medium",
    channel: "phone",
    serviceType: "helicopter",
    title: "Helicopter Transfer - London to Isle of Wight",
    description: "Helicopter transfer from Battersea to Isle of Wight. Party of 3. Weekend trip.",
    pickupLocation: "Battersea Heliport, London SW11",
    dropoffLocation: "Sandown Airport, Isle of Wight PO36",
    pickupDate: "2026-03-20T10:00:00Z",
    assigneeId: null,
    slaDueAt: "2026-03-18T12:00:00Z",
    createdAt: "2026-02-26T08:00:00Z",
    updatedAt: "2026-02-26T08:00:00Z",
  },
  {
    id: "conv-18",
    clientId: "cli-10",
    status: "in_review",
    priority: "high",
    channel: "concierge",
    serviceType: "car",
    title: "Phantom Fleet - Celebrity Client Event",
    description: "3x Rolls-Royce Phantoms for celebrity client arrivals at charity gala. Red carpet coordination required. Press management needed.",
    pickupLocation: "The Savoy, Strand, London WC2R",
    dropoffLocation: "Victoria and Albert Museum, Cromwell Road, London SW7",
    pickupDate: "2026-03-02T18:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-03-01T12:00:00Z",
    createdAt: "2026-02-12T10:00:00Z",
    updatedAt: "2026-02-25T14:30:00Z",
  },
  {
    id: "conv-19",
    clientId: "cli-10",
    status: "converted",
    priority: "medium",
    channel: "email",
    serviceType: "car",
    title: "S-Class - Heathrow to Mayfair",
    description: "Standard S-Class airport transfer. Terminal 5 arrivals. BA flight arriving international.",
    pickupLocation: "London Heathrow Airport (LHR), Terminal 5",
    dropoffLocation: "The Connaught, Carlos Place, Mayfair, London W1K",
    pickupDate: "2026-02-05T07:30:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-05T06:00:00Z",
    createdAt: "2026-02-03T09:00:00Z",
    updatedAt: "2026-02-05T08:45:00Z",
  },
  {
    id: "conv-20",
    clientId: "cli-11",
    status: "in_review",
    priority: "low",
    channel: "web",
    serviceType: "car",
    title: "BMW 7 Series - Heathrow to Surrey",
    description: "BMW 7 Series transfer from Heathrow to Surrey. Evening arrival. Client's first booking.",
    pickupLocation: "London Heathrow Airport (LHR), Terminal 4",
    dropoffLocation: "Virginia Water, Surrey GU25",
    pickupDate: "2026-03-08T21:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-03-07T18:00:00Z",
    createdAt: "2026-02-24T16:00:00Z",
    updatedAt: "2026-02-25T09:00:00Z",
  },
  {
    id: "conv-21",
    clientId: "cli-12",
    status: "in_review",
    priority: "medium",
    channel: "whatsapp",
    serviceType: "car",
    title: "Mercedes S-Class - Stansted to City of London",
    description: "S-Class with meet and greet from Stansted Airport to City of London office.",
    pickupLocation: "London Stansted Airport (STN), Arrivals",
    dropoffLocation: "30 St Mary Axe, City of London EC3A",
    pickupDate: "2026-03-03T14:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-03-02T10:00:00Z",
    createdAt: "2026-02-18T07:00:00Z",
    updatedAt: "2026-02-25T11:00:00Z",
  },
  {
    id: "conv-22",
    clientId: "cli-12",
    status: "new",
    priority: "high",
    channel: "phone",
    serviceType: "jet",
    title: "Hawker 800 - London to Birmingham",
    description: "Hawker 800XP for same-day round trip London to Birmingham. 6 passengers. Business meeting, return by evening.",
    pickupLocation: "Farnborough Airport (FAB), TAG Terminal",
    dropoffLocation: "Birmingham Airport (BHX), Private Terminal",
    pickupDate: "2026-03-10T06:00:00Z",
    assigneeId: null,
    slaDueAt: "2026-03-08T12:00:00Z",
    createdAt: "2026-02-26T10:00:00Z",
    updatedAt: "2026-02-26T10:00:00Z",
  },
  {
    id: "conv-23",
    clientId: "cli-1",
    status: "awaiting_client",
    priority: "critical",
    channel: "concierge",
    serviceType: "yacht",
    title: "Yacht Charter - Solent Summer (Follow-up)",
    description: "Follow-up arrangement for 60m yacht charter. Original booking requires additional tender and water toys. Client insists on specific captain from previous charter.",
    pickupLocation: "Southampton Marina, Hampshire",
    dropoffLocation: "Southampton Marina, Hampshire",
    pickupDate: "2026-07-15T12:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-26T14:00:00Z",
    createdAt: "2026-02-15T08:00:00Z",
    updatedAt: "2026-02-25T17:00:00Z",
  },
  {
    id: "conv-24",
    clientId: "cli-3",
    status: "closed",
    priority: "medium",
    channel: "email",
    serviceType: "car",
    title: "Bentley Bentayga - London Sightseeing (Cancelled)",
    description: "Originally requested Bentley Bentayga with driver for London sightseeing. Cancelled due to travel plan changes.",
    pickupLocation: "The Ritz London, Piccadilly, London W1J",
    dropoffLocation: "Kensington Palace, London W8",
    pickupDate: "2026-02-10T09:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-09T12:00:00Z",
    createdAt: "2026-01-30T14:00:00Z",
    updatedAt: "2026-02-07T16:00:00Z",
  },
];
