import type { Request } from "@/types";

export const requests: Request[] = [
  // VIP client requests (cli-1 through cli-4)
  {
    id: "req-1",
    clientId: "cli-1",
    status: "completed",
    priority: "critical",
    channel: "concierge",
    serviceType: "car",
    title: "Airport Transfer - Teterboro to Manhattan Penthouse",
    description: "Mr. Rothschild requires a Mercedes-Maybach S680 transfer from Teterboro Airport to his Manhattan residence. Chilled Krug Grande Cuvée must be stocked. Driver must be pre-approved by security team.",
    pickupLocation: "Teterboro Airport (TEB), Private Terminal",
    dropoffLocation: "432 Park Avenue, Penthouse, New York, NY",
    pickupDate: "2026-01-15T18:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-01-15T16:00:00Z",
    createdAt: "2026-01-14T10:00:00Z",
    updatedAt: "2026-01-15T19:30:00Z",
  },
  {
    id: "req-2",
    clientId: "cli-1",
    status: "in_progress",
    priority: "high",
    channel: "phone",
    serviceType: "jet",
    title: "Gulfstream G650 Charter - NYC to Aspen",
    description: "Weekend ski trip. Gulfstream G650 or equivalent. Party of 6 with extensive luggage and ski equipment. Catering from Nobu required onboard.",
    pickupLocation: "Teterboro Airport (TEB), Private Terminal",
    dropoffLocation: "Aspen/Pitkin County Airport (ASE)",
    pickupDate: "2026-02-28T08:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-27T20:00:00Z",
    createdAt: "2026-02-10T14:00:00Z",
    updatedAt: "2026-02-20T11:30:00Z",
  },
  {
    id: "req-3",
    clientId: "cli-2",
    status: "assigned",
    priority: "critical",
    channel: "whatsapp",
    serviceType: "helicopter",
    title: "Helicopter Transfer - Hong Kong to Macau",
    description: "Mrs. Cheng-Worthington requires helicopter transfer for casino event. AgustaWestland AW139 preferred. Landing at Grand Lisboa helipad. Return same evening.",
    pickupLocation: "The Peninsula Hong Kong, Helipad",
    dropoffLocation: "Grand Lisboa Hotel, Macau, Helipad",
    pickupDate: "2026-03-05T14:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-03-04T10:00:00Z",
    createdAt: "2026-02-18T09:00:00Z",
    updatedAt: "2026-02-19T15:20:00Z",
  },
  {
    id: "req-4",
    clientId: "cli-2",
    status: "completed",
    priority: "high",
    channel: "email",
    serviceType: "car",
    title: "Rolls-Royce Phantom Fleet - Wedding Convoy",
    description: "Fleet of 4 Rolls-Royce Phantoms for wedding party. White exteriors only. Floral arrangements by Floristry by Moens. Route from The Peninsula to St. John's Cathedral.",
    pickupLocation: "The Peninsula Hong Kong",
    dropoffLocation: "St. John's Cathedral, Hong Kong",
    pickupDate: "2026-01-20T10:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-01-19T12:00:00Z",
    createdAt: "2025-12-15T08:00:00Z",
    updatedAt: "2026-01-20T16:00:00Z",
  },
  {
    id: "req-5",
    clientId: "cli-3",
    status: "action_required",
    priority: "critical",
    channel: "concierge",
    serviceType: "yacht",
    title: "Superyacht Charter - Monaco Grand Prix Weekend",
    description: "80m+ superyacht for Monaco Grand Prix weekend. 12 guests. Must have harbor-facing position. Chef, crew, and entertainment to be arranged separately. Tender service required.",
    pickupLocation: "Port Hercules, Monaco",
    dropoffLocation: "Port Hercules, Monaco",
    pickupDate: "2026-05-22T12:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-25T18:00:00Z",
    createdAt: "2026-02-01T07:00:00Z",
    updatedAt: "2026-02-24T16:30:00Z",
  },
  {
    id: "req-6",
    clientId: "cli-3",
    status: "new",
    priority: "high",
    channel: "phone",
    serviceType: "jet",
    title: "BBJ 737 Charter - Dubai to London",
    description: "Boeing Business Jet for entourage of 20. Full bedroom suite required. Halal catering from specified provider. Landing at Farnborough.",
    pickupLocation: "Al Maktoum International Airport (DWC), Royal Terminal",
    dropoffLocation: "Farnborough Airport (FAB), TAG Terminal",
    pickupDate: "2026-03-15T06:00:00Z",
    assigneeId: null,
    slaDueAt: "2026-02-28T12:00:00Z",
    createdAt: "2026-02-24T11:00:00Z",
    updatedAt: "2026-02-24T11:00:00Z",
  },
  {
    id: "req-7",
    clientId: "cli-4",
    status: "in_progress",
    priority: "high",
    channel: "email",
    serviceType: "car",
    title: "Bentley Flying Spur - Paris Fashion Week",
    description: "Bentley Flying Spur with dedicated chauffeur for full Fashion Week schedule. 7-day rental. Must accommodate tight schedule changes. Driver fluent in French and English.",
    pickupLocation: "Le Bristol Paris, 112 Rue du Faubourg Saint-Honoré",
    dropoffLocation: "Various Fashion Week venues, Paris",
    pickupDate: "2026-03-01T08:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-02-28T18:00:00Z",
    createdAt: "2026-02-05T13:00:00Z",
    updatedAt: "2026-02-22T10:00:00Z",
  },
  {
    id: "req-8",
    clientId: "cli-4",
    status: "completed",
    priority: "medium",
    channel: "whatsapp",
    serviceType: "helicopter",
    title: "Helicopter Tour - Mont Blanc",
    description: "Scenic helicopter tour around Mont Blanc for Mme de Montfort and 3 guests. Champagne service. Landing at Megève for lunch at Flocons de Sel.",
    pickupLocation: "Chamonix Heliport",
    dropoffLocation: "Megève Altiport",
    pickupDate: "2026-01-25T11:00:00Z",
    assigneeId: "usr-5",
    slaDueAt: "2026-01-24T14:00:00Z",
    createdAt: "2026-01-10T16:00:00Z",
    updatedAt: "2026-01-25T17:00:00Z",
  },
  // Non-VIP client requests
  {
    id: "req-9",
    clientId: "cli-5",
    status: "completed",
    priority: "medium",
    channel: "web",
    serviceType: "car",
    title: "S-Class Transfer - LAX to Beverly Hills Hotel",
    description: "Mercedes S-Class transfer from LAX International Terminal. Meet and greet service. Luggage assistance for 3 bags.",
    pickupLocation: "Los Angeles International Airport (LAX), Terminal B",
    dropoffLocation: "The Beverly Hills Hotel, 9641 Sunset Blvd",
    pickupDate: "2026-01-18T20:00:00Z",
    assigneeId: "usr-5",
    slaDueAt: "2026-01-18T18:00:00Z",
    createdAt: "2026-01-16T09:00:00Z",
    updatedAt: "2026-01-18T21:30:00Z",
  },
  {
    id: "req-10",
    clientId: "cli-5",
    status: "new",
    priority: "low",
    channel: "email",
    serviceType: "car",
    title: "Executive Van - Corporate Event Shuttle",
    description: "Mercedes V-Class for corporate event. Shuttle service between hotel and convention center. 8-hour booking.",
    pickupLocation: "The Ritz-Carlton, Los Angeles",
    dropoffLocation: "Los Angeles Convention Center",
    pickupDate: "2026-03-10T07:00:00Z",
    assigneeId: null,
    slaDueAt: "2026-03-08T12:00:00Z",
    createdAt: "2026-02-25T14:00:00Z",
    updatedAt: "2026-02-25T14:00:00Z",
  },
  {
    id: "req-11",
    clientId: "cli-6",
    status: "in_progress",
    priority: "medium",
    channel: "phone",
    serviceType: "car",
    title: "Range Rover Autobiography - London to Cotswolds",
    description: "Range Rover Autobiography LWB for weekend countryside trip. Pick up from Claridge's. Return Sunday evening.",
    pickupLocation: "Claridge's, Brook Street, Mayfair, London",
    dropoffLocation: "Soho Farmhouse, Great Tew, Oxfordshire",
    pickupDate: "2026-03-07T09:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-03-06T12:00:00Z",
    createdAt: "2026-02-20T11:00:00Z",
    updatedAt: "2026-02-23T09:15:00Z",
  },
  {
    id: "req-12",
    clientId: "cli-6",
    status: "cancelled",
    priority: "low",
    channel: "email",
    serviceType: "jet",
    title: "Citation XLS - London to Nice (Cancelled)",
    description: "Originally requested Citation XLS charter. Client cancelled due to schedule change.",
    pickupLocation: "London Luton Airport (LTN), Signature FBO",
    dropoffLocation: "Nice Côte d'Azur Airport (NCE), Private Terminal",
    pickupDate: "2026-02-14T10:00:00Z",
    assigneeId: "usr-5",
    slaDueAt: "2026-02-13T08:00:00Z",
    createdAt: "2026-02-01T16:00:00Z",
    updatedAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "req-13",
    clientId: "cli-7",
    status: "completed",
    priority: "medium",
    channel: "web",
    serviceType: "car",
    title: "Tesla Model S Plaid - San Francisco Airport Transfer",
    description: "Tesla Model S Plaid from SFO to downtown office. Client prefers electric vehicles. Standard meet and greet.",
    pickupLocation: "San Francisco International Airport (SFO), Terminal 2",
    dropoffLocation: "555 California Street, San Francisco",
    pickupDate: "2026-01-22T15:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-01-22T13:00:00Z",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-01-22T16:30:00Z",
  },
  {
    id: "req-14",
    clientId: "cli-8",
    status: "assigned",
    priority: "high",
    channel: "whatsapp",
    serviceType: "jet",
    title: "Challenger 350 - Shanghai to Tokyo",
    description: "Bombardier Challenger 350 for business trip. Party of 4. Mandarin-speaking crew preferred. Specific catering requirements to follow.",
    pickupLocation: "Shanghai Hongqiao Airport (SHA), FBO",
    dropoffLocation: "Tokyo Haneda Airport (HND), Private Terminal",
    pickupDate: "2026-03-12T07:00:00Z",
    assigneeId: "usr-5",
    slaDueAt: "2026-03-10T12:00:00Z",
    createdAt: "2026-02-22T06:00:00Z",
    updatedAt: "2026-02-23T14:00:00Z",
  },
  {
    id: "req-15",
    clientId: "cli-8",
    status: "action_required",
    priority: "medium",
    channel: "email",
    serviceType: "car",
    title: "Maybach GLS 600 - Shanghai Full-Day Service",
    description: "Maybach GLS 600 with driver for full day in Shanghai. Client needs vehicle for multiple business meetings. Awaiting exact itinerary.",
    pickupLocation: "The Bund, Shanghai",
    dropoffLocation: "Pudong, Shanghai",
    pickupDate: "2026-03-13T08:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-02-26T10:00:00Z",
    createdAt: "2026-02-21T08:00:00Z",
    updatedAt: "2026-02-24T11:00:00Z",
  },
  {
    id: "req-16",
    clientId: "cli-9",
    status: "completed",
    priority: "low",
    channel: "web",
    serviceType: "car",
    title: "E-Class Transfer - São Paulo Airport",
    description: "Mercedes E-Class from Guarulhos Airport to Fasano Hotel. Portuguese-speaking driver.",
    pickupLocation: "São Paulo/Guarulhos International Airport (GRU)",
    dropoffLocation: "Hotel Fasano São Paulo, Rua Vittorio Fasano",
    pickupDate: "2026-01-28T22:00:00Z",
    assigneeId: "usr-5",
    slaDueAt: "2026-01-28T20:00:00Z",
    createdAt: "2026-01-25T12:00:00Z",
    updatedAt: "2026-01-28T23:15:00Z",
  },
  {
    id: "req-17",
    clientId: "cli-9",
    status: "new",
    priority: "medium",
    channel: "phone",
    serviceType: "helicopter",
    title: "Helicopter Transfer - São Paulo to Guarujá",
    description: "Helicopter transfer from São Paulo to beach house in Guarujá. Party of 3. Weekend trip.",
    pickupLocation: "Campo de Marte Airport, São Paulo",
    dropoffLocation: "Guarujá Helipad, São Paulo Coast",
    pickupDate: "2026-03-20T10:00:00Z",
    assigneeId: null,
    slaDueAt: "2026-03-18T12:00:00Z",
    createdAt: "2026-02-26T08:00:00Z",
    updatedAt: "2026-02-26T08:00:00Z",
  },
  {
    id: "req-18",
    clientId: "cli-10",
    status: "in_progress",
    priority: "high",
    channel: "concierge",
    serviceType: "car",
    title: "Phantom Fleet - Celebrity Client Event",
    description: "3x Rolls-Royce Phantoms for celebrity client arrivals at charity gala. Red carpet coordination required. Press management needed.",
    pickupLocation: "The Savoy, London",
    dropoffLocation: "Victoria and Albert Museum, London",
    pickupDate: "2026-03-02T18:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-03-01T12:00:00Z",
    createdAt: "2026-02-12T10:00:00Z",
    updatedAt: "2026-02-25T14:30:00Z",
  },
  {
    id: "req-19",
    clientId: "cli-10",
    status: "completed",
    priority: "medium",
    channel: "email",
    serviceType: "car",
    title: "S-Class - Heathrow to Mayfair",
    description: "Standard S-Class airport transfer. Terminal 5 arrivals. Flight BA117 from JFK.",
    pickupLocation: "London Heathrow Airport (LHR), Terminal 5",
    dropoffLocation: "The Connaught, Carlos Place, Mayfair, London",
    pickupDate: "2026-02-05T07:30:00Z",
    assigneeId: "usr-5",
    slaDueAt: "2026-02-05T06:00:00Z",
    createdAt: "2026-02-03T09:00:00Z",
    updatedAt: "2026-02-05T08:45:00Z",
  },
  {
    id: "req-20",
    clientId: "cli-11",
    status: "assigned",
    priority: "low",
    channel: "web",
    serviceType: "car",
    title: "BMW 7 Series - JFK to Greenwich",
    description: "BMW 7 Series transfer from JFK to Greenwich, CT. Evening arrival. Client's first booking.",
    pickupLocation: "John F. Kennedy International Airport (JFK), Terminal 4",
    dropoffLocation: "Greenwich, Connecticut",
    pickupDate: "2026-03-08T21:00:00Z",
    assigneeId: "usr-5",
    slaDueAt: "2026-03-07T18:00:00Z",
    createdAt: "2026-02-24T16:00:00Z",
    updatedAt: "2026-02-25T09:00:00Z",
  },
  {
    id: "req-21",
    clientId: "cli-12",
    status: "in_progress",
    priority: "medium",
    channel: "whatsapp",
    serviceType: "car",
    title: "Mercedes S-Class - Lagos to Victoria Island",
    description: "S-Class with security escort from Murtala Muhammed Airport to Victoria Island office. Armed escort required per company policy.",
    pickupLocation: "Murtala Muhammed International Airport (LOS), Lagos",
    dropoffLocation: "Eko Atlantic, Victoria Island, Lagos",
    pickupDate: "2026-03-03T14:00:00Z",
    assigneeId: "usr-4",
    slaDueAt: "2026-03-02T10:00:00Z",
    createdAt: "2026-02-18T07:00:00Z",
    updatedAt: "2026-02-25T11:00:00Z",
  },
  {
    id: "req-22",
    clientId: "cli-12",
    status: "new",
    priority: "high",
    channel: "phone",
    serviceType: "jet",
    title: "Hawker 800 - Lagos to Abuja",
    description: "Hawker 800XP for same-day round trip Lagos to Abuja. 6 passengers. Business meeting, return by evening.",
    pickupLocation: "Murtala Muhammed Airport (LOS), General Aviation Terminal",
    dropoffLocation: "Nnamdi Azikiwe International Airport (ABV), Abuja",
    pickupDate: "2026-03-10T06:00:00Z",
    assigneeId: null,
    slaDueAt: "2026-03-08T12:00:00Z",
    createdAt: "2026-02-26T10:00:00Z",
    updatedAt: "2026-02-26T10:00:00Z",
  },
  {
    id: "req-23",
    clientId: "cli-1",
    status: "action_required",
    priority: "critical",
    channel: "concierge",
    serviceType: "yacht",
    title: "Yacht Charter - Caribbean New Year's (Follow-up)",
    description: "Follow-up arrangement for 60m yacht charter. Original booking requires additional tender and water toys. Client insists on specific captain from previous charter.",
    pickupLocation: "St. Barths, Gustavia Harbor",
    dropoffLocation: "St. Barths, Gustavia Harbor",
    pickupDate: "2026-12-28T12:00:00Z",
    assigneeId: "usr-3",
    slaDueAt: "2026-02-26T14:00:00Z",
    createdAt: "2026-02-15T08:00:00Z",
    updatedAt: "2026-02-25T17:00:00Z",
  },
  {
    id: "req-24",
    clientId: "cli-3",
    status: "cancelled",
    priority: "medium",
    channel: "email",
    serviceType: "car",
    title: "Bentley Bentayga - Abu Dhabi City Tour (Cancelled)",
    description: "Originally requested Bentley Bentayga with driver for Abu Dhabi sightseeing. Cancelled due to travel plan changes.",
    pickupLocation: "Emirates Palace, Abu Dhabi",
    dropoffLocation: "Louvre Abu Dhabi, Saadiyat Island",
    pickupDate: "2026-02-10T09:00:00Z",
    assigneeId: "usr-5",
    slaDueAt: "2026-02-09T12:00:00Z",
    createdAt: "2026-01-30T14:00:00Z",
    updatedAt: "2026-02-07T16:00:00Z",
  },
];
